# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/kubernetesconfigurationextension/ci.yml
      - sdk/kubernetesconfigurationextension/azure-resourcemanager-kubernetesconfigurationextension/
    exclude:
      - sdk/kubernetesconfigurationextension/pom.xml
      - sdk/kubernetesconfigurationextension/azure-resourcemanager-kubernetesconfigurationextension/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/kubernetesconfigurationextension/ci.yml
      - sdk/kubernetesconfigurationextension/azure-resourcemanager-kubernetesconfigurationextension/
    exclude:
      - sdk/kubernetesconfigurationextension/pom.xml
      - sdk/kubernetesconfigurationextension/azure-resourcemanager-kubernetesconfigurationextension/pom.xml

parameters:
  - name: release_azureresourcemanagerkubernetesconfigurationextension
    displayName: azure-resourcemanager-kubernetesconfigurationextension
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: kubernetesconfigurationextension
    Artifacts:
      - name: azure-resourcemanager-kubernetesconfigurationextension
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerkubernetesconfigurationextension
        releaseInBatch: ${{ parameters.release_azureresourcemanagerkubernetesconfigurationextension }}
