# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/kubernetesruntime/ci.yml
      - sdk/kubernetesruntime/azure-resourcemanager-containerorchestratorruntime/
    exclude:
      - sdk/kubernetesruntime/pom.xml
      - sdk/kubernetesruntime/azure-resourcemanager-containerorchestratorruntime/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/kubernetesruntime/ci.yml
      - sdk/kubernetesruntime/azure-resourcemanager-containerorchestratorruntime/
    exclude:
      - sdk/kubernetesruntime/pom.xml
      - sdk/kubernetesruntime/azure-resourcemanager-containerorchestratorruntime/pom.xml

parameters:
  - name: release_azureresourcemanagercontainerorchestratorruntime
    displayName: azure-resourcemanager-containerorchestratorruntime
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: kubernetesruntime
    Artifacts:
      - name: azure-resourcemanager-containerorchestratorruntime
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagercontainerorchestratorruntime
        releaseInBatch: ${{ parameters.release_azureresourcemanagercontainerorchestratorruntime }}
