# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/manufacturingplatform/ci.yml
      - sdk/manufacturingplatform/azure-resourcemanager-manufacturingplatform/
    exclude:
      - sdk/manufacturingplatform/pom.xml
      - sdk/manufacturingplatform/azure-resourcemanager-manufacturingplatform/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/manufacturingplatform/ci.yml
      - sdk/manufacturingplatform/azure-resourcemanager-manufacturingplatform/
    exclude:
      - sdk/manufacturingplatform/pom.xml
      - sdk/manufacturingplatform/azure-resourcemanager-manufacturingplatform/pom.xml

parameters:
  - name: release_azureresourcemanagermanufacturingplatform
    displayName: azure-resourcemanager-manufacturingplatform
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: manufacturingplatform
    Artifacts:
      - name: azure-resourcemanager-manufacturingplatform
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagermanufacturingplatform
        releaseInBatch: ${{ parameters.release_azureresourcemanagermanufacturingplatform }}
