// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.dfp.fluent.models;

import com.azure.core.annotation.Fluent;
import com.azure.json.JsonReader;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import com.azure.resourcemanager.dfp.models.DfpInstanceAdministrators;
import com.azure.resourcemanager.dfp.models.ProvisioningState;
import java.io.IOException;

/**
 * Properties of DFP resource.
 */
@Fluent
public final class DfpInstanceProperties extends DfpInstanceMutableProperties {
    /*
     * The current deployment state of DFP resource. The provisioningState is to indicate states for resource
     * provisioning.
     */
    private ProvisioningState provisioningState;

    /**
     * Creates an instance of DfpInstanceProperties class.
     */
    public DfpInstanceProperties() {
    }

    /**
     * Get the provisioningState property: The current deployment state of DFP resource. The provisioningState is to
     * indicate states for resource provisioning.
     * 
     * @return the provisioningState value.
     */
    public ProvisioningState provisioningState() {
        return this.provisioningState;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DfpInstanceProperties withAdministration(DfpInstanceAdministrators administration) {
        super.withAdministration(administration);
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    @Override
    public void validate() {
        if (administration() != null) {
            administration().validate();
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeJsonField("administration", administration());
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of DfpInstanceProperties from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of DfpInstanceProperties if the JsonReader was pointing to an instance of it, or null if it
     * was pointing to JSON null.
     * @throws IOException If an error occurs while reading the DfpInstanceProperties.
     */
    public static DfpInstanceProperties fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            DfpInstanceProperties deserializedDfpInstanceProperties = new DfpInstanceProperties();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("administration".equals(fieldName)) {
                    deserializedDfpInstanceProperties.withAdministration(DfpInstanceAdministrators.fromJson(reader));
                } else if ("provisioningState".equals(fieldName)) {
                    deserializedDfpInstanceProperties.provisioningState
                        = ProvisioningState.fromString(reader.getString());
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedDfpInstanceProperties;
        });
    }
}
