// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.machinelearning.implementation;

import com.azure.core.management.SystemData;
import com.azure.resourcemanager.machinelearning.fluent.models.AccountModelInner;
import com.azure.resourcemanager.machinelearning.models.AccountModel;
import com.azure.resourcemanager.machinelearning.models.CallRateLimit;
import com.azure.resourcemanager.machinelearning.models.DeploymentModel;
import com.azure.resourcemanager.machinelearning.models.ModelDeprecationInfo;
import com.azure.resourcemanager.machinelearning.models.ModelLifecycleStatus;
import com.azure.resourcemanager.machinelearning.models.ModelSku;
import java.util.Collections;
import java.util.List;
import java.util.Map;

public final class AccountModelImpl implements AccountModel {
    private AccountModelInner innerObject;

    private final com.azure.resourcemanager.machinelearning.MachineLearningManager serviceManager;

    AccountModelImpl(AccountModelInner innerObject,
        com.azure.resourcemanager.machinelearning.MachineLearningManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String format() {
        return this.innerModel().format();
    }

    public String name() {
        return this.innerModel().name();
    }

    public String version() {
        return this.innerModel().version();
    }

    public String source() {
        return this.innerModel().source();
    }

    public CallRateLimit callRateLimit() {
        return this.innerModel().callRateLimit();
    }

    public DeploymentModel baseModel() {
        return this.innerModel().baseModel();
    }

    public List<String> connectionIds() {
        List<String> inner = this.innerModel().connectionIds();
        if (inner != null) {
            return Collections.unmodifiableList(inner);
        } else {
            return Collections.emptyList();
        }
    }

    public Boolean isDefaultVersion() {
        return this.innerModel().isDefaultVersion();
    }

    public List<ModelSku> skus() {
        List<ModelSku> inner = this.innerModel().skus();
        if (inner != null) {
            return Collections.unmodifiableList(inner);
        } else {
            return Collections.emptyList();
        }
    }

    public Integer maxCapacity() {
        return this.innerModel().maxCapacity();
    }

    public Map<String, String> capabilities() {
        Map<String, String> inner = this.innerModel().capabilities();
        if (inner != null) {
            return Collections.unmodifiableMap(inner);
        } else {
            return Collections.emptyMap();
        }
    }

    public Map<String, String> finetuneCapabilities() {
        Map<String, String> inner = this.innerModel().finetuneCapabilities();
        if (inner != null) {
            return Collections.unmodifiableMap(inner);
        } else {
            return Collections.emptyMap();
        }
    }

    public ModelDeprecationInfo deprecation() {
        return this.innerModel().deprecation();
    }

    public ModelLifecycleStatus lifecycleStatus() {
        return this.innerModel().lifecycleStatus();
    }

    public SystemData systemData() {
        return this.innerModel().systemData();
    }

    public AccountModelInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.machinelearning.MachineLearningManager manager() {
        return this.serviceManager;
    }
}
