# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/azuredata/ci.yml
      - sdk/azuredata/azure-resourcemanager-azuredata/
    exclude:
      - sdk/azuredata/pom.xml
      - sdk/azuredata/azure-resourcemanager-azuredata/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/azuredata/ci.yml
      - sdk/azuredata/azure-resourcemanager-azuredata/
    exclude:
      - sdk/azuredata/pom.xml
      - sdk/azuredata/azure-resourcemanager-azuredata/pom.xml

parameters:
  - name: release_azureresourcemanagerazuredata
    displayName: azure-resourcemanager-azuredata
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: azuredata
    EnableBatchRelease: true
    Artifacts:
      - name: azure-resourcemanager-azuredata
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerazuredata
        releaseInBatch: ${{ parameters.release_azureresourcemanagerazuredata }}
