// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.spatio.implementation.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.annotation.Generated;
import com.azure.spatio.models.FileDetails;

/**
 * The CreateOrReplaceRequest model.
 */
@Fluent
public final class CreateOrReplaceRequest {
    /*
     * TODO: add description for file
     */
    @Generated
    private FileDetails file;

    /*
     * TODO: add description for data
     */
    @Generated
    private final String data;

    /**
     * Creates an instance of CreateOrReplaceRequest class.
     * 
     * @param data the data value to set.
     */
    @Generated
    public CreateOrReplaceRequest(String data) {
        this.data = data;
    }

    /**
     * Get the file property: TODO: add description for file.
     * 
     * @return the file value.
     */
    @Generated
    public FileDetails getFile() {
        return this.file;
    }

    /**
     * Set the file property: TODO: add description for file.
     * 
     * @param file the file value to set.
     * @return the CreateOrReplaceRequest object itself.
     */
    @Generated
    public CreateOrReplaceRequest setFile(FileDetails file) {
        this.file = file;
        return this;
    }

    /**
     * Get the data property: TODO: add description for data.
     * 
     * @return the data value.
     */
    @Generated
    public String getData() {
        return this.data;
    }
}
