# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/mission/ci.yml
      - sdk/mission/azure-resourcemanager-mission/
    exclude:
      - sdk/mission/pom.xml
      - sdk/mission/azure-resourcemanager-mission/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/mission/ci.yml
      - sdk/mission/azure-resourcemanager-mission/
    exclude:
      - sdk/mission/pom.xml
      - sdk/mission/azure-resourcemanager-mission/pom.xml

parameters:
  - name: release_azureresourcemanagermission
    displayName: azure-resourcemanager-mission
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: mission
    Artifacts:
      - name: azure-resourcemanager-mission
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagermission
        releaseInBatch: ${{ parameters.release_azureresourcemanagermission }}
