# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/azurelogistics/ci.yml
      - sdk/azurelogistics/azure-resourcemanager-azurelogistics/
    exclude:
      - sdk/azurelogistics/pom.xml
      - sdk/azurelogistics/azure-resourcemanager-azurelogistics/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/azurelogistics/ci.yml
      - sdk/azurelogistics/azure-resourcemanager-azurelogistics/
    exclude:
      - sdk/azurelogistics/pom.xml
      - sdk/azurelogistics/azure-resourcemanager-azurelogistics/pom.xml

parameters:
  - name: release_azureresourcemanagerazurelogistics
    displayName: azure-resourcemanager-azurelogistics
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: azurelogistics
    EnableBatchRelease: true
    Artifacts:
      - name: azure-resourcemanager-azurelogistics
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerazurelogistics
        releaseInBatch: ${{ parameters.release_azureresourcemanagerazurelogistics }}
