// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.migration.assessment.models;

import com.azure.core.http.rest.PagedIterable;
import com.azure.core.http.rest.Response;
import com.azure.core.util.Context;

/**
 * Resource collection API of AssessedWebAppsV3Operations.
 */
public interface AssessedWebAppsV3Operations {
    /**
     * List AssessedWebAppV3 resources by WebAppAssessmentV3.
     * 
     * @param resourceGroupName The name of the resource group. The name is case insensitive.
     * @param projectName Assessment Project Name.
     * @param assessmentName WebApp Assessment ARM name.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response of a AssessedWebAppV3 list operation as paginated response with {@link PagedIterable}.
     */
    PagedIterable<AssessedWebAppV3> listByParent(String resourceGroupName, String projectName, String assessmentName);

    /**
     * List AssessedWebAppV3 resources by WebAppAssessmentV3.
     * 
     * @param resourceGroupName The name of the resource group. The name is case insensitive.
     * @param projectName Assessment Project Name.
     * @param assessmentName WebApp Assessment ARM name.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response of a AssessedWebAppV3 list operation as paginated response with {@link PagedIterable}.
     */
    PagedIterable<AssessedWebAppV3> listByParent(String resourceGroupName, String projectName, String assessmentName,
        Context context);

    /**
     * Get a AssessedWebAppV3.
     * 
     * @param resourceGroupName The name of the resource group. The name is case insensitive.
     * @param projectName Assessment Project Name.
     * @param assessmentName WebApp Assessment ARM name.
     * @param assessedWebAppName Assessed web app ARM name.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return a AssessedWebAppV3 along with {@link Response}.
     */
    Response<AssessedWebAppV3> getWithResponse(String resourceGroupName, String projectName, String assessmentName,
        String assessedWebAppName, Context context);

    /**
     * Get a AssessedWebAppV3.
     * 
     * @param resourceGroupName The name of the resource group. The name is case insensitive.
     * @param projectName Assessment Project Name.
     * @param assessmentName WebApp Assessment ARM name.
     * @param assessedWebAppName Assessed web app ARM name.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return a AssessedWebAppV3.
     */
    AssessedWebAppV3 get(String resourceGroupName, String projectName, String assessmentName,
        String assessedWebAppName);
}
