// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.migration.assessment.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.util.logging.ClientLogger;
import com.azure.json.JsonReader;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;

/**
 * Representation of a vsphere management licence.
 */
@Fluent
public final class VsphereManagementLicense extends VsphereLicenseBase {
    /*
     * VSphere licence type.
     */
    private VsphereManagementLicenseType licenseType;

    /**
     * Creates an instance of VsphereManagementLicense class.
     */
    public VsphereManagementLicense() {
    }

    /**
     * Get the licenseType property: VSphere licence type.
     * 
     * @return the licenseType value.
     */
    public VsphereManagementLicenseType licenseType() {
        return this.licenseType;
    }

    /**
     * Set the licenseType property: VSphere licence type.
     * 
     * @param licenseType the licenseType value to set.
     * @return the VsphereManagementLicense object itself.
     */
    public VsphereManagementLicense withLicenseType(VsphereManagementLicenseType licenseType) {
        this.licenseType = licenseType;
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VsphereManagementLicense withLicenseCost(float licenseCost) {
        super.withLicenseCost(licenseCost);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VsphereManagementLicense withBasicSupportCost(float basicSupportCost) {
        super.withBasicSupportCost(basicSupportCost);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VsphereManagementLicense withProductionSupportCost(float productionSupportCost) {
        super.withProductionSupportCost(productionSupportCost);
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    @Override
    public void validate() {
        if (licenseType() == null) {
            throw LOGGER.atError()
                .log(new IllegalArgumentException(
                    "Missing required property licenseType in model VsphereManagementLicense"));
        }
    }

    private static final ClientLogger LOGGER = new ClientLogger(VsphereManagementLicense.class);

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeFloatField("licenseCost", licenseCost());
        jsonWriter.writeFloatField("basicSupportCost", basicSupportCost());
        jsonWriter.writeFloatField("productionSupportCost", productionSupportCost());
        jsonWriter.writeStringField("licenseType", this.licenseType == null ? null : this.licenseType.toString());
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of VsphereManagementLicense from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of VsphereManagementLicense if the JsonReader was pointing to an instance of it, or null if
     * it was pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the VsphereManagementLicense.
     */
    public static VsphereManagementLicense fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            VsphereManagementLicense deserializedVsphereManagementLicense = new VsphereManagementLicense();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("licenseCost".equals(fieldName)) {
                    deserializedVsphereManagementLicense.withLicenseCost(reader.getFloat());
                } else if ("basicSupportCost".equals(fieldName)) {
                    deserializedVsphereManagementLicense.withBasicSupportCost(reader.getFloat());
                } else if ("productionSupportCost".equals(fieldName)) {
                    deserializedVsphereManagementLicense.withProductionSupportCost(reader.getFloat());
                } else if ("licenseType".equals(fieldName)) {
                    deserializedVsphereManagementLicense.licenseType
                        = VsphereManagementLicenseType.fromString(reader.getString());
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedVsphereManagementLicense;
        });
    }
}
