# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/mysqldiscovery/ci.yml
      - sdk/mysqldiscovery/azure-resourcemanager-mysqldiscovery/
    exclude:
      - sdk/mysqldiscovery/pom.xml
      - sdk/mysqldiscovery/azure-resourcemanager-mysqldiscovery/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/mysqldiscovery/ci.yml
      - sdk/mysqldiscovery/azure-resourcemanager-mysqldiscovery/
    exclude:
      - sdk/mysqldiscovery/pom.xml
      - sdk/mysqldiscovery/azure-resourcemanager-mysqldiscovery/pom.xml

parameters:
  - name: release_azureresourcemanagermysqldiscovery
    displayName: azure-resourcemanager-mysqldiscovery
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: mysqldiscovery
    Artifacts:
      - name: azure-resourcemanager-mysqldiscovery
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagermysqldiscovery
        releaseInBatch: ${{ parameters.release_azureresourcemanagermysqldiscovery }}
