// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.speechingestion.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.annotation.Generated;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Map;

/**
 * LanguageIdentificationProperties model.
 */
@Fluent
public final class LanguageIdentificationPropertiesModel {
    /*
     * mode
     */
    @Generated
    @JsonProperty(value = "mode")
    private String mode;

    /*
     * candidateLocales.
     */
    @Generated
    @JsonProperty(value = "candidateLocales")
    private List<String> candidateLocales;

    /*
     * speechModelMapping
     */
    @Generated
    @JsonProperty(value = "speechModelMapping")
    private Map<String, EntityReferenceModel> speechModelMapping;

    /**
     * Creates an instance of LanguageIdentificationPropertiesModel class.
     * 
     * @param mode the mode value to set.
     * @param candidateLocales the candidateLocales value to set.
     */
    @Generated
    @JsonCreator
    public LanguageIdentificationPropertiesModel(@JsonProperty(value = "mode") String mode,
        @JsonProperty(value = "candidateLocales") List<String> candidateLocales) {
        this.mode = mode;
        this.candidateLocales = candidateLocales;
    }

    /**
     * Get the mode property: mode.
     * 
     * @return the mode value.
     */
    @Generated
    public String getMode() {
        return this.mode;
    }

    /**
     * Get the candidateLocales property: candidateLocales.
     * 
     * @return the candidateLocales value.
     */
    @Generated
    public List<String> getCandidateLocales() {
        return this.candidateLocales;
    }

    /**
     * Get the speechModelMapping property: speechModelMapping.
     * 
     * @return the speechModelMapping value.
     */
    @Generated
    public Map<String, EntityReferenceModel> getSpeechModelMapping() {
        return this.speechModelMapping;
    }

    /**
     * Set the speechModelMapping property: speechModelMapping.
     * 
     * @param speechModelMapping the speechModelMapping value to set.
     * @return the LanguageIdentificationPropertiesModel object itself.
     */
    @Generated
    public LanguageIdentificationPropertiesModel
        setSpeechModelMapping(Map<String, EntityReferenceModel> speechModelMapping) {
        this.speechModelMapping = speechModelMapping;
        return this;
    }
}
