# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/intelligentdataexperiences/ci.yml
      - sdk/intelligentdataexperiences/azure-resourcemanager-intelligentdataexperiences/
    exclude:
      - sdk/intelligentdataexperiences/pom.xml
      - sdk/intelligentdataexperiences/azure-resourcemanager-intelligentdataexperiences/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/intelligentdataexperiences/ci.yml
      - sdk/intelligentdataexperiences/azure-resourcemanager-intelligentdataexperiences/
    exclude:
      - sdk/intelligentdataexperiences/pom.xml
      - sdk/intelligentdataexperiences/azure-resourcemanager-intelligentdataexperiences/pom.xml

parameters:
  - name: release_azureresourcemanagerintelligentdataexperiences
    displayName: azure-resourcemanager-intelligentdataexperiences
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: intelligentdataexperiences
    EnableBatchRelease: true
    Artifacts:
      - name: azure-resourcemanager-intelligentdataexperiences
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerintelligentdataexperiences
        releaseInBatch: ${{ parameters.release_azureresourcemanagerintelligentdataexperiences }}
