// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.iotfirmwaredefense.models;

import com.azure.core.annotation.Fluent;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;

/**
 * Binary hardening of a firmware.
 */
@Fluent
public final class BinaryHardeningResult implements JsonSerializable<BinaryHardeningResult> {
    /*
     * ID for the binary hardening result.
     */
    private String binaryHardeningId;

    /*
     * The security hardening features of the binary.
     */
    private BinaryHardeningFeatures securityHardeningFeatures;

    /*
     * The architecture of the binary being reported on.
     */
    private String executableArchitecture;

    /*
     * The path to the binary in the firmware.
     */
    private String filePath;

    /*
     * The executable class to indicate 32 or 64 bit.
     */
    private ExecutableClass executableClass;

    /*
     * The runpath property of the uploaded binary, which is a method of specifying additional paths to load objects at
     * runtime.
     */
    private String runpath;

    /*
     * The rpath property of the uploaded binary, which is a deprecated method of specifying additional paths to load
     * objects at runtime.
     */
    private String rpath;

    /*
     * The status of the last operation.
     */
    private ProvisioningState provisioningState;

    /**
     * Creates an instance of BinaryHardeningResult class.
     */
    public BinaryHardeningResult() {
    }

    /**
     * Get the binaryHardeningId property: ID for the binary hardening result.
     * 
     * @return the binaryHardeningId value.
     */
    public String binaryHardeningId() {
        return this.binaryHardeningId;
    }

    /**
     * Set the binaryHardeningId property: ID for the binary hardening result.
     * 
     * @param binaryHardeningId the binaryHardeningId value to set.
     * @return the BinaryHardeningResult object itself.
     */
    public BinaryHardeningResult withBinaryHardeningId(String binaryHardeningId) {
        this.binaryHardeningId = binaryHardeningId;
        return this;
    }

    /**
     * Get the securityHardeningFeatures property: The security hardening features of the binary.
     * 
     * @return the securityHardeningFeatures value.
     */
    public BinaryHardeningFeatures securityHardeningFeatures() {
        return this.securityHardeningFeatures;
    }

    /**
     * Set the securityHardeningFeatures property: The security hardening features of the binary.
     * 
     * @param securityHardeningFeatures the securityHardeningFeatures value to set.
     * @return the BinaryHardeningResult object itself.
     */
    public BinaryHardeningResult withSecurityHardeningFeatures(BinaryHardeningFeatures securityHardeningFeatures) {
        this.securityHardeningFeatures = securityHardeningFeatures;
        return this;
    }

    /**
     * Get the executableArchitecture property: The architecture of the binary being reported on.
     * 
     * @return the executableArchitecture value.
     */
    public String executableArchitecture() {
        return this.executableArchitecture;
    }

    /**
     * Set the executableArchitecture property: The architecture of the binary being reported on.
     * 
     * @param executableArchitecture the executableArchitecture value to set.
     * @return the BinaryHardeningResult object itself.
     */
    public BinaryHardeningResult withExecutableArchitecture(String executableArchitecture) {
        this.executableArchitecture = executableArchitecture;
        return this;
    }

    /**
     * Get the filePath property: The path to the binary in the firmware.
     * 
     * @return the filePath value.
     */
    public String filePath() {
        return this.filePath;
    }

    /**
     * Set the filePath property: The path to the binary in the firmware.
     * 
     * @param filePath the filePath value to set.
     * @return the BinaryHardeningResult object itself.
     */
    public BinaryHardeningResult withFilePath(String filePath) {
        this.filePath = filePath;
        return this;
    }

    /**
     * Get the executableClass property: The executable class to indicate 32 or 64 bit.
     * 
     * @return the executableClass value.
     */
    public ExecutableClass executableClass() {
        return this.executableClass;
    }

    /**
     * Set the executableClass property: The executable class to indicate 32 or 64 bit.
     * 
     * @param executableClass the executableClass value to set.
     * @return the BinaryHardeningResult object itself.
     */
    public BinaryHardeningResult withExecutableClass(ExecutableClass executableClass) {
        this.executableClass = executableClass;
        return this;
    }

    /**
     * Get the runpath property: The runpath property of the uploaded binary, which is a method of specifying additional
     * paths to load objects at runtime.
     * 
     * @return the runpath value.
     */
    public String runpath() {
        return this.runpath;
    }

    /**
     * Set the runpath property: The runpath property of the uploaded binary, which is a method of specifying additional
     * paths to load objects at runtime.
     * 
     * @param runpath the runpath value to set.
     * @return the BinaryHardeningResult object itself.
     */
    public BinaryHardeningResult withRunpath(String runpath) {
        this.runpath = runpath;
        return this;
    }

    /**
     * Get the rpath property: The rpath property of the uploaded binary, which is a deprecated method of specifying
     * additional paths to load objects at runtime.
     * 
     * @return the rpath value.
     */
    public String rpath() {
        return this.rpath;
    }

    /**
     * Set the rpath property: The rpath property of the uploaded binary, which is a deprecated method of specifying
     * additional paths to load objects at runtime.
     * 
     * @param rpath the rpath value to set.
     * @return the BinaryHardeningResult object itself.
     */
    public BinaryHardeningResult withRpath(String rpath) {
        this.rpath = rpath;
        return this;
    }

    /**
     * Get the provisioningState property: The status of the last operation.
     * 
     * @return the provisioningState value.
     */
    public ProvisioningState provisioningState() {
        return this.provisioningState;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (securityHardeningFeatures() != null) {
            securityHardeningFeatures().validate();
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("binaryHardeningId", this.binaryHardeningId);
        jsonWriter.writeJsonField("securityHardeningFeatures", this.securityHardeningFeatures);
        jsonWriter.writeStringField("executableArchitecture", this.executableArchitecture);
        jsonWriter.writeStringField("filePath", this.filePath);
        jsonWriter.writeStringField("executableClass",
            this.executableClass == null ? null : this.executableClass.toString());
        jsonWriter.writeStringField("runpath", this.runpath);
        jsonWriter.writeStringField("rpath", this.rpath);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of BinaryHardeningResult from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of BinaryHardeningResult if the JsonReader was pointing to an instance of it, or null if it
     * was pointing to JSON null.
     * @throws IOException If an error occurs while reading the BinaryHardeningResult.
     */
    public static BinaryHardeningResult fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            BinaryHardeningResult deserializedBinaryHardeningResult = new BinaryHardeningResult();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("binaryHardeningId".equals(fieldName)) {
                    deserializedBinaryHardeningResult.binaryHardeningId = reader.getString();
                } else if ("securityHardeningFeatures".equals(fieldName)) {
                    deserializedBinaryHardeningResult.securityHardeningFeatures
                        = BinaryHardeningFeatures.fromJson(reader);
                } else if ("executableArchitecture".equals(fieldName)) {
                    deserializedBinaryHardeningResult.executableArchitecture = reader.getString();
                } else if ("filePath".equals(fieldName)) {
                    deserializedBinaryHardeningResult.filePath = reader.getString();
                } else if ("executableClass".equals(fieldName)) {
                    deserializedBinaryHardeningResult.executableClass = ExecutableClass.fromString(reader.getString());
                } else if ("runpath".equals(fieldName)) {
                    deserializedBinaryHardeningResult.runpath = reader.getString();
                } else if ("rpath".equals(fieldName)) {
                    deserializedBinaryHardeningResult.rpath = reader.getString();
                } else if ("provisioningState".equals(fieldName)) {
                    deserializedBinaryHardeningResult.provisioningState
                        = ProvisioningState.fromString(reader.getString());
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedBinaryHardeningResult;
        });
    }
}
