# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/rnr/ci.yml
      - sdk/rnr/azure-resourcemanager-marketplace/
    exclude:
      - sdk/rnr/pom.xml
      - sdk/rnr/azure-resourcemanager-marketplace/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/rnr/ci.yml
      - sdk/rnr/azure-resourcemanager-marketplace/
    exclude:
      - sdk/rnr/pom.xml
      - sdk/rnr/azure-resourcemanager-marketplace/pom.xml

parameters:
  - name: release_azureresourcemanagermarketplace
    displayName: azure-resourcemanager-marketplace
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: rnr
    Artifacts:
      - name: azure-resourcemanager-marketplace
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagermarketplace
        releaseInBatch: ${{ parameters.release_azureresourcemanagermarketplace }}
