# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/monitormicrosoftmonitorpipelinegroups/ci.yml
      - sdk/monitormicrosoftmonitorpipelinegroups/azure-resourcemanager-monitormicrosoftmonitorpipelinegroups/
    exclude:
      - sdk/monitormicrosoftmonitorpipelinegroups/pom.xml
      - sdk/monitormicrosoftmonitorpipelinegroups/azure-resourcemanager-monitormicrosoftmonitorpipelinegroups/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/monitormicrosoftmonitorpipelinegroups/ci.yml
      - sdk/monitormicrosoftmonitorpipelinegroups/azure-resourcemanager-monitormicrosoftmonitorpipelinegroups/
    exclude:
      - sdk/monitormicrosoftmonitorpipelinegroups/pom.xml
      - sdk/monitormicrosoftmonitorpipelinegroups/azure-resourcemanager-monitormicrosoftmonitorpipelinegroups/pom.xml

parameters:
  - name: release_azureresourcemanagermonitormicrosoftmonitorpipelinegroups
    displayName: azure-resourcemanager-monitormicrosoftmonitorpipelinegroups
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: monitormicrosoftmonitorpipelinegroups
    Artifacts:
      - name: azure-resourcemanager-monitormicrosoftmonitorpipelinegroups
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagermonitormicrosoftmonitorpipelinegroups
        releaseInBatch: ${{ parameters.release_azureresourcemanagermonitormicrosoftmonitorpipelinegroups }}
