// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.machinelearning.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeId;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The PackageInputPathBase model.
 */
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    property = "inputPathType",
    defaultImpl = PackageInputPathBase.class,
    visible = true)
@JsonTypeName("PackageInputPathBase")
@JsonSubTypes({
    @JsonSubTypes.Type(name = "PathId", value = PackageInputPathId.class),
    @JsonSubTypes.Type(name = "Url", value = PackageInputPathUrl.class),
    @JsonSubTypes.Type(name = "PathVersion", value = PackageInputPathVersion.class) })
@Immutable
public class PackageInputPathBase {
    /*
     * [Required] Input path type for package inputs.
     */
    @JsonTypeId
    @JsonProperty(value = "inputPathType", required = true)
    private InputPathType inputPathType;

    /**
     * Creates an instance of PackageInputPathBase class.
     */
    public PackageInputPathBase() {
        this.inputPathType = InputPathType.fromString("PackageInputPathBase");
    }

    /**
     * Get the inputPathType property: [Required] Input path type for package inputs.
     * 
     * @return the inputPathType value.
     */
    public InputPathType inputPathType() {
        return this.inputPathType;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }
}
