# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/awsconnector/ci.yml
      - sdk/awsconnector/azure-resourcemanager-awsconnector/
    exclude:
      - sdk/awsconnector/pom.xml
      - sdk/awsconnector/azure-resourcemanager-awsconnector/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/awsconnector/ci.yml
      - sdk/awsconnector/azure-resourcemanager-awsconnector/
    exclude:
      - sdk/awsconnector/pom.xml
      - sdk/awsconnector/azure-resourcemanager-awsconnector/pom.xml

parameters:
  - name: release_azureresourcemanagerawsconnector
    displayName: azure-resourcemanager-awsconnector
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: awsconnector
    Artifacts:
      - name: azure-resourcemanager-awsconnector
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerawsconnector
        releaseInBatch: ${{ parameters.release_azureresourcemanagerawsconnector }}
