// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.awsconnector.implementation;

import com.azure.core.management.Region;
import com.azure.core.management.SystemData;
import com.azure.core.util.Context;
import com.azure.resourcemanager.awsconnector.fluent.models.Route53HostedZoneInner;
import com.azure.resourcemanager.awsconnector.models.Route53HostedZone;
import com.azure.resourcemanager.awsconnector.models.Route53HostedZoneProperties;
import com.azure.resourcemanager.awsconnector.models.Route53HostedZoneTagsUpdate;
import java.util.Collections;
import java.util.Map;

public final class Route53HostedZoneImpl
    implements Route53HostedZone, Route53HostedZone.Definition, Route53HostedZone.Update {
    private Route53HostedZoneInner innerObject;

    private final com.azure.resourcemanager.awsconnector.AwsconnectorManager serviceManager;

    public String id() {
        return this.innerModel().id();
    }

    public String name() {
        return this.innerModel().name();
    }

    public String type() {
        return this.innerModel().type();
    }

    public String location() {
        return this.innerModel().location();
    }

    public Map<String, String> tags() {
        Map<String, String> inner = this.innerModel().tags();
        if (inner != null) {
            return Collections.unmodifiableMap(inner);
        } else {
            return Collections.emptyMap();
        }
    }

    public Route53HostedZoneProperties properties() {
        return this.innerModel().properties();
    }

    public SystemData systemData() {
        return this.innerModel().systemData();
    }

    public Region region() {
        return Region.fromName(this.regionName());
    }

    public String regionName() {
        return this.location();
    }

    public String resourceGroupName() {
        return resourceGroupName;
    }

    public Route53HostedZoneInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.awsconnector.AwsconnectorManager manager() {
        return this.serviceManager;
    }

    private String resourceGroupName;

    private String name;

    private Route53HostedZoneTagsUpdate updateProperties;

    public Route53HostedZoneImpl withExistingResourceGroup(String resourceGroupName) {
        this.resourceGroupName = resourceGroupName;
        return this;
    }

    public Route53HostedZone create() {
        this.innerObject = serviceManager.serviceClient()
            .getRoute53HostedZones()
            .createOrReplace(resourceGroupName, name, this.innerModel(), Context.NONE);
        return this;
    }

    public Route53HostedZone create(Context context) {
        this.innerObject = serviceManager.serviceClient()
            .getRoute53HostedZones()
            .createOrReplace(resourceGroupName, name, this.innerModel(), context);
        return this;
    }

    Route53HostedZoneImpl(String name, com.azure.resourcemanager.awsconnector.AwsconnectorManager serviceManager) {
        this.innerObject = new Route53HostedZoneInner();
        this.serviceManager = serviceManager;
        this.name = name;
    }

    public Route53HostedZoneImpl update() {
        this.updateProperties = new Route53HostedZoneTagsUpdate();
        return this;
    }

    public Route53HostedZone apply() {
        this.innerObject = serviceManager.serviceClient()
            .getRoute53HostedZones()
            .update(resourceGroupName, name, updateProperties, Context.NONE);
        return this;
    }

    public Route53HostedZone apply(Context context) {
        this.innerObject = serviceManager.serviceClient()
            .getRoute53HostedZones()
            .update(resourceGroupName, name, updateProperties, context);
        return this;
    }

    Route53HostedZoneImpl(Route53HostedZoneInner innerObject,
        com.azure.resourcemanager.awsconnector.AwsconnectorManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
        this.resourceGroupName = ResourceManagerUtils.getValueFromIdByName(innerObject.id(), "resourceGroups");
        this.name = ResourceManagerUtils.getValueFromIdByName(innerObject.id(), "route53HostedZones");
    }

    public Route53HostedZone refresh() {
        this.innerObject = serviceManager.serviceClient()
            .getRoute53HostedZones()
            .getByResourceGroupWithResponse(resourceGroupName, name, Context.NONE)
            .getValue();
        return this;
    }

    public Route53HostedZone refresh(Context context) {
        this.innerObject = serviceManager.serviceClient()
            .getRoute53HostedZones()
            .getByResourceGroupWithResponse(resourceGroupName, name, context)
            .getValue();
        return this;
    }

    public Route53HostedZoneImpl withRegion(Region location) {
        this.innerModel().withLocation(location.toString());
        return this;
    }

    public Route53HostedZoneImpl withRegion(String location) {
        this.innerModel().withLocation(location);
        return this;
    }

    public Route53HostedZoneImpl withTags(Map<String, String> tags) {
        if (isInCreateMode()) {
            this.innerModel().withTags(tags);
            return this;
        } else {
            this.updateProperties.withTags(tags);
            return this;
        }
    }

    public Route53HostedZoneImpl withProperties(Route53HostedZoneProperties properties) {
        this.innerModel().withProperties(properties);
        return this;
    }

    private boolean isInCreateMode() {
        return this.innerModel().id() == null;
    }
}
