# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/healthdataaiservices/ci.yml
      - sdk/healthdataaiservices/azure-health-deidentification/
    exclude:
      - sdk/healthdataaiservices/pom.xml
      - sdk/healthdataaiservices/azure-health-deidentification/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/healthdataaiservices/ci.yml
      - sdk/healthdataaiservices/azure-health-deidentification/
    exclude:
      - sdk/healthdataaiservices/pom.xml
      - sdk/healthdataaiservices/azure-health-deidentification/pom.xml

parameters:
  - name: release_azurehealthdeidentification
    displayName: azure-health-deidentification
    type: boolean
    default: true

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: healthdataaiservices
    Artifacts:
      - name: azure-health-deidentification
        groupId: com.azure
        safeName: azurehealthdeidentification
        releaseInBatch: ${{ parameters.release_azurehealthdeidentification }}
