# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/healthdataaiservices/ci.yml
      - sdk/healthdataaiservices/azure-resourcemanager-healthdataaiservices/
    exclude:
      - sdk/healthdataaiservices/pom.xml
      - sdk/healthdataaiservices/azure-resourcemanager-healthdataaiservices/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/healthdataaiservices/ci.yml
      - sdk/healthdataaiservices/azure-resourcemanager-healthdataaiservices/
    exclude:
      - sdk/healthdataaiservices/pom.xml
      - sdk/healthdataaiservices/azure-resourcemanager-healthdataaiservices/pom.xml

parameters:
  - name: release_azureresourcemanagerhealthdataaiservices
    displayName: azure-resourcemanager-healthdataaiservices
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: healthdataaiservices
    Artifacts:
      - name: azure-resourcemanager-healthdataaiservices
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerhealthdataaiservices
        releaseInBatch: ${{ parameters.release_azureresourcemanagerhealthdataaiservices }}
