# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/scheduler/ci.yml
      - sdk/scheduler/azure-resourcemanager-scheduler/
    exclude:
      - sdk/scheduler/pom.xml
      - sdk/scheduler/azure-resourcemanager-scheduler/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/scheduler/ci.yml
      - sdk/scheduler/azure-resourcemanager-scheduler/
    exclude:
      - sdk/scheduler/pom.xml
      - sdk/scheduler/azure-resourcemanager-scheduler/pom.xml

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: scheduler
    Artifacts:
      - name: azure-resourcemanager-scheduler
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerscheduler
