# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/resourcesmicrosoftresourcesdeploymentstacks/ci.yml
      - sdk/resourcesmicrosoftresourcesdeploymentstacks/azure-resourcemanager-resourcesmicrosoftresourcesdeploymentstacks/
    exclude:
      - sdk/resourcesmicrosoftresourcesdeploymentstacks/pom.xml
      - sdk/resourcesmicrosoftresourcesdeploymentstacks/azure-resourcemanager-resourcesmicrosoftresourcesdeploymentstacks/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/resourcesmicrosoftresourcesdeploymentstacks/ci.yml
      - sdk/resourcesmicrosoftresourcesdeploymentstacks/azure-resourcemanager-resourcesmicrosoftresourcesdeploymentstacks/
    exclude:
      - sdk/resourcesmicrosoftresourcesdeploymentstacks/pom.xml
      - sdk/resourcesmicrosoftresourcesdeploymentstacks/azure-resourcemanager-resourcesmicrosoftresourcesdeploymentstacks/pom.xml

parameters:
  - name: release_azureresourcemanagerresourcesmicrosoftresourcesdeploymentstacks
    displayName: azure-resourcemanager-resourcesmicrosoftresourcesdeploymentstacks
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: resourcesmicrosoftresourcesdeploymentstacks
    Artifacts:
      - name: azure-resourcemanager-resourcesmicrosoftresourcesdeploymentstacks
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerresourcesmicrosoftresourcesdeploymentstacks
        releaseInBatch: ${{ parameters.release_azureresourcemanagerresourcesmicrosoftresourcesdeploymentstacks }}
