# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/kubernetesconfigurationmicrosoftkubernetesconfigurationfluxconfigurations/ci.yml
      - sdk/kubernetesconfigurationmicrosoftkubernetesconfigurationfluxconfigurations/azure-resourcemanager-kubernetesconfigurationmicrosoftkubernetesconfigurationfluxconfigurations/
    exclude:
      - sdk/kubernetesconfigurationmicrosoftkubernetesconfigurationfluxconfigurations/pom.xml
      - sdk/kubernetesconfigurationmicrosoftkubernetesconfigurationfluxconfigurations/azure-resourcemanager-kubernetesconfigurationmicrosoftkubernetesconfigurationfluxconfigurations/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/kubernetesconfigurationmicrosoftkubernetesconfigurationfluxconfigurations/ci.yml
      - sdk/kubernetesconfigurationmicrosoftkubernetesconfigurationfluxconfigurations/azure-resourcemanager-kubernetesconfigurationmicrosoftkubernetesconfigurationfluxconfigurations/
    exclude:
      - sdk/kubernetesconfigurationmicrosoftkubernetesconfigurationfluxconfigurations/pom.xml
      - sdk/kubernetesconfigurationmicrosoftkubernetesconfigurationfluxconfigurations/azure-resourcemanager-kubernetesconfigurationmicrosoftkubernetesconfigurationfluxconfigurations/pom.xml

parameters:
  - name: release_azureresourcemanagerkubernetesconfigurationmicrosoftkubernetesconfigurationfluxconfigurations
    displayName: azure-resourcemanager-kubernetesconfigurationmicrosoftkubernetesconfigurationfluxconfigurations
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: kubernetesconfigurationmicrosoftkubernetesconfigurationfluxconfigurations
    Artifacts:
      - name: azure-resourcemanager-kubernetesconfigurationmicrosoftkubernetesconfigurationfluxconfigurations
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerkubernetesconfigurationmicrosoftkubernetesconfigurationfluxconfigurations
        releaseInBatch: ${{ parameters.release_azureresourcemanagerkubernetesconfigurationmicrosoftkubernetesconfigurationfluxconfigurations }}
