// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.networkcloud.models;

import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collection;

/**
 * The status representing the lifecycle stage of the edge cluster.
 */
public final class EdgeClusterLifecycleStatus extends ExpandableStringEnum<EdgeClusterLifecycleStatus> {
    /**
     * Static value Defined for EdgeClusterLifecycleStatus.
     */
    public static final EdgeClusterLifecycleStatus DEFINED = fromString("Defined");

    /**
     * Static value ControlPlaneOnly for EdgeClusterLifecycleStatus.
     */
    public static final EdgeClusterLifecycleStatus CONTROL_PLANE_ONLY = fromString("ControlPlaneOnly");

    /**
     * Static value Upgrading for EdgeClusterLifecycleStatus.
     */
    public static final EdgeClusterLifecycleStatus UPGRADING = fromString("Upgrading");

    /**
     * Static value Ready for EdgeClusterLifecycleStatus.
     */
    public static final EdgeClusterLifecycleStatus READY = fromString("Ready");

    /**
     * Static value Deleting for EdgeClusterLifecycleStatus.
     */
    public static final EdgeClusterLifecycleStatus DELETING = fromString("Deleting");

    /**
     * Creates a new instance of EdgeClusterLifecycleStatus value.
     * 
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Deprecated
    public EdgeClusterLifecycleStatus() {
    }

    /**
     * Creates or finds a EdgeClusterLifecycleStatus from its string representation.
     * 
     * @param name a name to look for.
     * @return the corresponding EdgeClusterLifecycleStatus.
     */
    @JsonCreator
    public static EdgeClusterLifecycleStatus fromString(String name) {
        return fromString(name, EdgeClusterLifecycleStatus.class);
    }

    /**
     * Gets known EdgeClusterLifecycleStatus values.
     * 
     * @return known EdgeClusterLifecycleStatus values.
     */
    public static Collection<EdgeClusterLifecycleStatus> values() {
        return values(EdgeClusterLifecycleStatus.class);
    }
}
