# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/codesigning/ci.yml
      - sdk/codesigning/com.azure.developer.signing/
    exclude:
      - sdk/codesigning/pom.xml
      - sdk/codesigning/com.azure.developer.signing/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/codesigning/ci.yml
      - sdk/codesigning/com.azure.developer.signing/
    exclude:
      - sdk/codesigning/pom.xml
      - sdk/codesigning/com.azure.developer.signing/pom.xml

parameters:
  - name: release_com.azure.developer.signing
    displayName: com.azure.developer.signing
    type: boolean
    default: true

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: codesigning
    EnableBatchRelease: true
    Artifacts:
      - name: com.azure.developer.signing
        groupId: com.azure
        safeName: com.azure.developer.signing
        releaseInBatch: ${{ parameters.release_com.azure.developer.signing }}
