# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/arizeaiobservabilityeval/ci.yml
      - sdk/arizeaiobservabilityeval/azure-resourceManager-arizeaiobservabilityeval/
    exclude:
      - sdk/arizeaiobservabilityeval/pom.xml
      - sdk/arizeaiobservabilityeval/azure-resourceManager-arizeaiobservabilityeval/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/arizeaiobservabilityeval/ci.yml
      - sdk/arizeaiobservabilityeval/azure-resourceManager-arizeaiobservabilityeval/
    exclude:
      - sdk/arizeaiobservabilityeval/pom.xml
      - sdk/arizeaiobservabilityeval/azure-resourceManager-arizeaiobservabilityeval/pom.xml

parameters:
  - name: release_azureresourceManagerarizeaiobservabilityeval
    displayName: azure-resourceManager-arizeaiobservabilityeval
    type: boolean
    default: true

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: arizeaiobservabilityeval
    Artifacts:
      - name: azure-resourceManager-arizeaiobservabilityeval
        groupId: com.azure.resourcemanager
        safeName: azureresourceManagerarizeaiobservabilityeval
        releaseInBatch: ${{ parameters.release_azureresourceManagerarizeaiobservabilityeval }}
