# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/cts/ci.yml
      - sdk/cts/azure-resourcemanager-cts/
    exclude:
      - sdk/cts/pom.xml
      - sdk/cts/azure-resourcemanager-cts/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/cts/ci.yml
      - sdk/cts/azure-resourcemanager-cts/
    exclude:
      - sdk/cts/pom.xml
      - sdk/cts/azure-resourcemanager-cts/pom.xml

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: cts
    Artifacts:
      - name: azure-resourcemanager-cts
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagercts
