# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/carbon/ci.yml
      - sdk/carbon/azure-resourcemanager-carbon/
    exclude:
      - sdk/carbon/pom.xml
      - sdk/carbon/azure-resourcemanager-carbon/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/carbon/ci.yml
      - sdk/carbon/azure-resourcemanager-carbon/
    exclude:
      - sdk/carbon/pom.xml
      - sdk/carbon/azure-resourcemanager-carbon/pom.xml

parameters:
  - name: release_azureresourcemanagercarbon
    displayName: azure-resourcemanager-carbon
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: carbon
    EnableBatchRelease: true
    Artifacts:
      - name: azure-resourcemanager-carbon
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagercarbon
        releaseInBatch: ${{ parameters.release_azureresourcemanagercarbon }}
