# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/scom/ci.yml
      - sdk/scom/azure-resourcemanager-scom/
    exclude:
      - sdk/scom/pom.xml
      - sdk/scom/azure-resourcemanager-scom/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/scom/ci.yml
      - sdk/scom/azure-resourcemanager-scom/
    exclude:
      - sdk/scom/pom.xml
      - sdk/scom/azure-resourcemanager-scom/pom.xml

parameters:
  - name: release_azureresourcemanagerscom
    displayName: azure-resourcemanager-scom
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: scom
    EnableBatchRelease: true
    Artifacts:
      - name: azure-resourcemanager-scom
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerscom
        releaseInBatch: ${{ parameters.release_azureresourcemanagerscom }}
