// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.communication.jobrouter.models;

import com.azure.communication.jobrouter.implementation.JsonMergePatchHelper;
import com.azure.core.annotation.Fluent;
import com.azure.core.annotation.Generated;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;
import java.util.HashSet;
import java.util.Set;

/**
 * An attachment which attaches worker selectors to a job.
 */
@Fluent
public class WorkerSelectorAttachment implements JsonSerializable<WorkerSelectorAttachment> {

    /*
     * The type discriminator describing a sub-type of WorkerSelectorAttachment.
     */
    @Generated
    private String kind = "WorkerSelectorAttachment";

    /**
     * Stores updated model property, the value is property name, not serialized name.
     */
    @Generated
    private final Set<String> updatedProperties = new HashSet<>();

    @Generated
    private boolean jsonMergePatch;

    @Generated
    private void serializeAsJsonMergePatch(boolean jsonMergePatch) {
        this.jsonMergePatch = jsonMergePatch;
    }

    static {
        JsonMergePatchHelper
            .setWorkerSelectorAttachmentAccessor(new JsonMergePatchHelper.WorkerSelectorAttachmentAccessor() {

                @Override
                public WorkerSelectorAttachment prepareModelForJsonMergePatch(WorkerSelectorAttachment model,
                    boolean jsonMergePatchEnabled) {
                    model.serializeAsJsonMergePatch(jsonMergePatchEnabled);
                    return model;
                }

                @Override
                public boolean isJsonMergePatch(WorkerSelectorAttachment model) {
                    return model.jsonMergePatch;
                }

                @Override
                public void setWorkerSelectorAttachmentKind(WorkerSelectorAttachment model,
                    WorkerSelectorAttachmentKind workerSelectorAttachmentKind) {
                    model.workerSelectorAttachmentKind = workerSelectorAttachmentKind;
                }
            });
    }

    /**
     * Creates an instance of WorkerSelectorAttachment class.
     */
    @Generated
    public WorkerSelectorAttachment() {
    }

    /**
     * Get the kind property: The type discriminator describing a sub-type of WorkerSelectorAttachment.
     *
     * @return the kind value.
     */
    @Generated
    public String getKind() {
        return this.kind;
    }

    /**
     * {@inheritDoc}
     */
    @Generated
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        if (jsonMergePatch) {
            return toJsonMergePatch(jsonWriter);
        } else {
            jsonWriter.writeStartObject();
            jsonWriter.writeStringField("kind", this.kind);
            jsonWriter.writeStringField("workerSelectorAttachmentKind",
                this.workerSelectorAttachmentKind == null ? null : this.workerSelectorAttachmentKind.toString());
            return jsonWriter.writeEndObject();
        }
    }

    @Generated
    private JsonWriter toJsonMergePatch(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("kind", this.kind);
        if (updatedProperties.contains("workerSelectorAttachmentKind")) {
            if (this.workerSelectorAttachmentKind == null) {
                jsonWriter.writeNullField("workerSelectorAttachmentKind");
            } else {
                jsonWriter.writeStringField("workerSelectorAttachmentKind",
                    this.workerSelectorAttachmentKind.toString());
            }
        }
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of WorkerSelectorAttachment from the JsonReader.
     *
     * @param jsonReader The JsonReader being read.
     * @return An instance of WorkerSelectorAttachment if the JsonReader was pointing to an instance of it, or null if
     * it was pointing to JSON null.
     * @throws IOException If an error occurs while reading the WorkerSelectorAttachment.
     */
    @Generated
    public static WorkerSelectorAttachment fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            String discriminatorValue = null;
            try (JsonReader readerToUse = reader.bufferObject()) {
                // Prepare for reading
                readerToUse.nextToken();
                while (readerToUse.nextToken() != JsonToken.END_OBJECT) {
                    String fieldName = readerToUse.getFieldName();
                    readerToUse.nextToken();
                    if ("kind".equals(fieldName)) {
                        discriminatorValue = readerToUse.getString();
                        break;
                    } else {
                        readerToUse.skipChildren();
                    }
                }
                // Use the discriminator value to determine which subtype should be deserialized.
                if ("conditional".equals(discriminatorValue)) {
                    return ConditionalWorkerSelectorAttachment.fromJson(readerToUse.reset());
                } else if ("passThrough".equals(discriminatorValue)) {
                    return PassThroughWorkerSelectorAttachment.fromJson(readerToUse.reset());
                } else if ("ruleEngine".equals(discriminatorValue)) {
                    return RuleEngineWorkerSelectorAttachment.fromJson(readerToUse.reset());
                } else if ("static".equals(discriminatorValue)) {
                    return StaticWorkerSelectorAttachment.fromJson(readerToUse.reset());
                } else if ("weightedAllocation".equals(discriminatorValue)) {
                    return WeightedAllocationWorkerSelectorAttachment.fromJson(readerToUse.reset());
                } else {
                    return fromJsonKnownDiscriminator(readerToUse.reset());
                }
            }
        });
    }

    @Generated
    static WorkerSelectorAttachment fromJsonKnownDiscriminator(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            WorkerSelectorAttachment deserializedWorkerSelectorAttachment = new WorkerSelectorAttachment();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();
                if ("kind".equals(fieldName)) {
                    deserializedWorkerSelectorAttachment.kind = reader.getString();
                } else if ("workerSelectorAttachmentKind".equals(fieldName)) {
                    deserializedWorkerSelectorAttachment.workerSelectorAttachmentKind
                        = WorkerSelectorAttachmentKind.fromString(reader.getString());
                } else {
                    reader.skipChildren();
                }
            }
            return deserializedWorkerSelectorAttachment;
        });
    }

    /*
     * The type discriminator describing a sub-type of WorkerSelectorAttachment.
     */
    @Generated
    private WorkerSelectorAttachmentKind workerSelectorAttachmentKind;

    /**
     * Get the workerSelectorAttachmentKind property: The type discriminator describing a sub-type of
     * WorkerSelectorAttachment.
     *
     * @return the workerSelectorAttachmentKind value.
     */
    @Generated
    public WorkerSelectorAttachmentKind getWorkerSelectorAttachmentKind() {
        return this.workerSelectorAttachmentKind;
    }

    /**
     * Set the workerSelectorAttachmentKind property: The type discriminator describing a sub-type of
     * WorkerSelectorAttachment.
     * <p>Required when create the resource.</p>
     *
     * @param workerSelectorAttachmentKind the workerSelectorAttachmentKind value to set.
     * @return the WorkerSelectorAttachment object itself.
     */
    @Generated
    public WorkerSelectorAttachment
        setWorkerSelectorAttachmentKind(WorkerSelectorAttachmentKind workerSelectorAttachmentKind) {
        this.workerSelectorAttachmentKind = workerSelectorAttachmentKind;
        this.updatedProperties.add("workerSelectorAttachmentKind");
        return this;
    }
}
