// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.synapse.fluent.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.util.logging.ClientLogger;
import com.azure.resourcemanager.synapse.models.Usage;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** The List Usages operation response. */
@Fluent
public final class ListUsagesResultInner {
    /*
     * The list of resource usages.
     */
    @JsonProperty(value = "value", required = true)
    private List<Usage> value;

    /** Creates an instance of ListUsagesResultInner class. */
    public ListUsagesResultInner() {
    }

    /**
     * Get the value property: The list of resource usages.
     *
     * @return the value value.
     */
    public List<Usage> value() {
        return this.value;
    }

    /**
     * Set the value property: The list of resource usages.
     *
     * @param value the value value to set.
     * @return the ListUsagesResultInner object itself.
     */
    public ListUsagesResultInner withValue(List<Usage> value) {
        this.value = value;
        return this;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (value() == null) {
            throw LOGGER
                .logExceptionAsError(
                    new IllegalArgumentException("Missing required property value in model ListUsagesResultInner"));
        } else {
            value().forEach(e -> e.validate());
        }
    }

    private static final ClientLogger LOGGER = new ClientLogger(ListUsagesResultInner.class);
}
