# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/managedservices/ci.yml
      - sdk/managedservices/azure-resourcemanager-managedservices/
    exclude:
      - sdk/managedservices/pom.xml
      - sdk/managedservices/azure-resourcemanager-managedservices/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/managedservices/ci.yml
      - sdk/managedservices/azure-resourcemanager-managedservices/
    exclude:
      - sdk/managedservices/pom.xml
      - sdk/managedservices/azure-resourcemanager-managedservices/pom.xml

parameters:
  - name: release_azureresourcemanagermanagedservices
    displayName: azure-resourcemanager-managedservices
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: managedservices
    EnableBatchRelease: true
    Artifacts:
      - name: azure-resourcemanager-managedservices
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagermanagedservices
        releaseInBatch: ${{ parameters.release_azureresourcemanagermanagedservices }}
