# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/ai/ci.yml
      - sdk/ai/azure-resourcemanager-ai/
    exclude:
      - sdk/ai/pom.xml
      - sdk/ai/azure-resourcemanager-ai/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/ai/ci.yml
      - sdk/ai/azure-resourcemanager-ai/
    exclude:
      - sdk/ai/pom.xml
      - sdk/ai/azure-resourcemanager-ai/pom.xml

parameters:
  - name: release_azureresourcemanagerai
    displayName: azure-resourcemanager-ai
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: ai
    EnableBatchRelease: true
    Artifacts:
      - name: azure-resourcemanager-ai
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerai
        releaseInBatch: ${{ parameters.release_azureresourcemanagerai }}
