# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/monitorpipelinegroups/ci.yml
      - sdk/monitorpipelinegroups/azure-resourcemanager-monitorpipelinegroups/
    exclude:
      - sdk/monitorpipelinegroups/pom.xml
      - sdk/monitorpipelinegroups/azure-resourcemanager-monitorpipelinegroups/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/monitorpipelinegroups/ci.yml
      - sdk/monitorpipelinegroups/azure-resourcemanager-monitorpipelinegroups/
    exclude:
      - sdk/monitorpipelinegroups/pom.xml
      - sdk/monitorpipelinegroups/azure-resourcemanager-monitorpipelinegroups/pom.xml

parameters:
  - name: release_azureresourcemanagermonitorpipelinegroups
    displayName: azure-resourcemanager-monitorpipelinegroups
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: monitorpipelinegroups
    Artifacts:
      - name: azure-resourcemanager-monitorpipelinegroups
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagermonitorpipelinegroups
        releaseInBatch: ${{ parameters.release_azureresourcemanagermonitorpipelinegroups }}
