# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/programmableconnectivity/ci.yml
      - sdk/programmableconnectivity/azure-programmableconnectivity/
    exclude:
      - sdk/programmableconnectivity/pom.xml
      - sdk/programmableconnectivity/azure-programmableconnectivity/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/programmableconnectivity/ci.yml
      - sdk/programmableconnectivity/azure-programmableconnectivity/
    exclude:
      - sdk/programmableconnectivity/pom.xml
      - sdk/programmableconnectivity/azure-programmableconnectivity/pom.xml

parameters:
  - name: release_azureprogrammableconnectivity
    displayName: azure-programmableconnectivity
    type: boolean
    default: true

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: programmableconnectivity
    Artifacts:
      - name: azure-programmableconnectivity
        groupId: com.azure
        safeName: azureprogrammableconnectivity
        releaseInBatch: ${{ parameters.release_azureprogrammableconnectivity }}
