# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/windowsiot/ci.yml
      - sdk/windowsiot/azure-resourcemanager-windowsiot/
    exclude:
      - sdk/windowsiot/pom.xml
      - sdk/windowsiot/azure-resourcemanager-windowsiot/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/windowsiot/ci.yml
      - sdk/windowsiot/azure-resourcemanager-windowsiot/
    exclude:
      - sdk/windowsiot/pom.xml
      - sdk/windowsiot/azure-resourcemanager-windowsiot/pom.xml

parameters:
  - name: release_azureresourcemanagerwindowsiot
    displayName: azure-resourcemanager-windowsiot
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: windowsiot
    EnableBatchRelease: true
    Artifacts:
      - name: azure-resourcemanager-windowsiot
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerwindowsiot
        releaseInBatch: ${{ parameters.release_azureresourcemanagerwindowsiot }}
