# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/sovereign/ci.yml
      - sdk/sovereign/azure-resourcemanager-sovereign/
    exclude:
      - sdk/sovereign/pom.xml
      - sdk/sovereign/azure-resourcemanager-sovereign/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/sovereign/ci.yml
      - sdk/sovereign/azure-resourcemanager-sovereign/
    exclude:
      - sdk/sovereign/pom.xml
      - sdk/sovereign/azure-resourcemanager-sovereign/pom.xml

parameters:
  - name: release_azureresourcemanagersovereign
    displayName: azure-resourcemanager-sovereign
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: sovereign
    Artifacts:
      - name: azure-resourcemanager-sovereign
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagersovereign
        releaseInBatch: ${{ parameters.release_azureresourcemanagersovereign }}
