# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/azurefleet/ci.yml
      - sdk/azurefleet/azure-resourcemanager-azurefleet/
    exclude:
      - sdk/azurefleet/pom.xml
      - sdk/azurefleet/azure-resourcemanager-azurefleet/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/azurefleet/ci.yml
      - sdk/azurefleet/azure-resourcemanager-azurefleet/
    exclude:
      - sdk/azurefleet/pom.xml
      - sdk/azurefleet/azure-resourcemanager-azurefleet/pom.xml

parameters:
  - name: release_azureresourcemanagerazurefleet
    displayName: azure-resourcemanager-azurefleet
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: azurefleet
    Artifacts:
      - name: azure-resourcemanager-azurefleet
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerazurefleet
        releaseInBatch: ${{ parameters.release_azureresourcemanagerazurefleet }}
