// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.databox.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeId;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Properties of data center and transport preference validation response.
 */
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    property = "validationType",
    defaultImpl = PreferencesValidationResponseProperties.class,
    visible = true)
@JsonTypeName("ValidatePreferences")
@Immutable
public final class PreferencesValidationResponseProperties extends ValidationInputResponse {
    /*
     * Identifies the type of validation response.
     */
    @JsonTypeId
    @JsonProperty(value = "validationType", required = true)
    private ValidationInputDiscriminator validationType = ValidationInputDiscriminator.VALIDATE_PREFERENCES;

    /*
     * Validation status of requested data center and transport.
     */
    @JsonProperty(value = "status", access = JsonProperty.Access.WRITE_ONLY)
    private ValidationStatus status;

    /**
     * Creates an instance of PreferencesValidationResponseProperties class.
     */
    public PreferencesValidationResponseProperties() {
    }

    /**
     * Get the validationType property: Identifies the type of validation response.
     * 
     * @return the validationType value.
     */
    @Override
    public ValidationInputDiscriminator validationType() {
        return this.validationType;
    }

    /**
     * Get the status property: Validation status of requested data center and transport.
     * 
     * @return the status value.
     */
    public ValidationStatus status() {
        return this.status;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    @Override
    public void validate() {
        super.validate();
    }
}
