# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/cloudshell/ci.yml
      - sdk/cloudshell/azure-resourcemanager-cloudshell/
    exclude:
      - sdk/cloudshell/pom.xml
      - sdk/cloudshell/azure-resourcemanager-cloudshell/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/cloudshell/ci.yml
      - sdk/cloudshell/azure-resourcemanager-cloudshell/
    exclude:
      - sdk/cloudshell/pom.xml
      - sdk/cloudshell/azure-resourcemanager-cloudshell/pom.xml

parameters:
  - name: release_azureresourcemanagercloudshell
    displayName: azure-resourcemanager-cloudshell
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: cloudshell
    EnableBatchRelease: true
    Artifacts:
      - name: azure-resourcemanager-cloudshell
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagercloudshell
        releaseInBatch: ${{ parameters.release_azureresourcemanagercloudshell }}
