# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/edgemicrosoftedgeedge/ci.yml
      - sdk/edgemicrosoftedgeedge/azure-resourcemanager-edgemicrosoftedgeedge/
    exclude:
      - sdk/edgemicrosoftedgeedge/pom.xml
      - sdk/edgemicrosoftedgeedge/azure-resourcemanager-edgemicrosoftedgeedge/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/edgemicrosoftedgeedge/ci.yml
      - sdk/edgemicrosoftedgeedge/azure-resourcemanager-edgemicrosoftedgeedge/
    exclude:
      - sdk/edgemicrosoftedgeedge/pom.xml
      - sdk/edgemicrosoftedgeedge/azure-resourcemanager-edgemicrosoftedgeedge/pom.xml

parameters:
  - name: release_azureresourcemanageredgemicrosoftedgeedge
    displayName: azure-resourcemanager-edgemicrosoftedgeedge
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: edgemicrosoftedgeedge
    Artifacts:
      - name: azure-resourcemanager-edgemicrosoftedgeedge
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanageredgemicrosoftedgeedge
        releaseInBatch: ${{ parameters.release_azureresourcemanageredgemicrosoftedgeedge }}
