# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/servicebus/ci.yml
      - sdk/servicebus/azure-messaging-servicebus/
      - sdk/servicebus/azure-messaging-servicebus-stress/
      - sdk/servicebus/azure-messaging-servicebus-track1-perf/
      - sdk/servicebus/azure-messaging-servicebus-track2-perf/
      - sdk/servicebus/build/
    exclude:
      - sdk/servicebus/pom.xml
      - sdk/servicebus/azure-messaging-servicebus/pom.xml
      - sdk/servicebus/azure-messaging-servicebus-stress/pom.xml
      - sdk/servicebus/azure-messaging-servicebus-track1-perf/pom.xml
      - sdk/servicebus/azure-messaging-servicebus-track2-perf/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/servicebus/ci.yml
      - sdk/servicebus/azure-messaging-servicebus/
      - sdk/servicebus/azure-messaging-servicebus-stress/
      - sdk/servicebus/azure-messaging-servicebus-track1-perf/
      - sdk/servicebus/azure-messaging-servicebus-track2-perf/
      - sdk/servicebus/build/
    exclude:
      - sdk/servicebus/pom.xml
      - sdk/servicebus/azure-messaging-servicebus/pom.xml
      - sdk/servicebus/azure-messaging-servicebus-stress/pom.xml
      - sdk/servicebus/azure-messaging-servicebus-track1-perf/pom.xml
      - sdk/servicebus/azure-messaging-servicebus-track2-perf/pom.xml

parameters:
  - name: release_dependsonlivetests
    displayName: Release depends on live tests
    type: boolean
    default: true
  - name: release_azureresourcemanagerservicebusgenerated
    displayName: azure-resourcemanager-servicebus-generated
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: servicebus
    Artifacts:
      - name: azure-messaging-servicebus
        groupId: com.azure
        safeName: azuremessagingservicebus
      - name: azure-resourcemanager-servicebus-generated
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerservicebusgenerated
        releaseInBatch: ${{ parameters.release_azureresourcemanagerservicebusgenerated }}
    AdditionalModules:
      - name: azure-messaging-servicebus-track1-perf
        groupId: com.azure
      - name: azure-messaging-servicebus-track2-perf
        groupId: com.azure
      - name: perf-test-core
        groupId: com.azure
