# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/azuredatatransfer/ci.yml
      - sdk/azuredatatransfer/azure-resourcemanager-azuredatatransfer/
    exclude:
      - sdk/azuredatatransfer/pom.xml
      - sdk/azuredatatransfer/azure-resourcemanager-azuredatatransfer/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/azuredatatransfer/ci.yml
      - sdk/azuredatatransfer/azure-resourcemanager-azuredatatransfer/
    exclude:
      - sdk/azuredatatransfer/pom.xml
      - sdk/azuredatatransfer/azure-resourcemanager-azuredatatransfer/pom.xml

parameters:
  - name: release_azureresourcemanagerazuredatatransfer
    displayName: azure-resourcemanager-azuredatatransfer
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: azuredatatransfer
    Artifacts:
      - name: azure-resourcemanager-azuredatatransfer
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerazuredatatransfer
        releaseInBatch: ${{ parameters.release_azureresourcemanagerazuredatatransfer }}
