# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/documentintelligence/ci.yml
      - sdk/documentintelligence/azure-ai-documentintelligence/
    exclude:
      - sdk/documentintelligence/pom.xml
      - sdk/documentintelligence/azure-ai-documentintelligence/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/documentintelligence/ci.yml
      - sdk/documentintelligence/azure-ai-documentintelligence/
    exclude:
      - sdk/documentintelligence/pom.xml
      - sdk/documentintelligence/azure-ai-documentintelligence/pom.xml

parameters:
  - name: release_azureaidocumentintelligence
    displayName: azure-ai-documentintelligence
    type: boolean
    default: true

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: documentintelligence
    EnableBatchRelease: true
    Artifacts:
      - name: azure-ai-documentintelligence
        groupId: com.azure
        safeName: azureaidocumentintelligence
        releaseInBatch: ${{ parameters.release_azureaidocumentintelligence }}
