# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/apicenter/ci.yml
      - sdk/apicenter/azure-resourcemanager-apicenter/
    exclude:
      - sdk/apicenter/pom.xml
      - sdk/apicenter/azure-resourcemanager-apicenter/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/apicenter/ci.yml
      - sdk/apicenter/azure-resourcemanager-apicenter/
    exclude:
      - sdk/apicenter/pom.xml
      - sdk/apicenter/azure-resourcemanager-apicenter/pom.xml

parameters:
  - name: release_azureresourcemanagerapicenter
    displayName: azure-resourcemanager-apicenter
    type: boolean
    default: false
  - name: release_azureapicenter
    displayName: azure-apicenter
    type: boolean
    default: true

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: apicenter
    Artifacts:
      - name: azure-resourcemanager-apicenter
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerapicenter
        releaseInBatch: ${{ parameters.release_azureresourcemanagerapicenter }}
      - name: azure-apicenter
        groupId: com.azure
        safeName: azureapicenter
        releaseInBatch: ${{ parameters.release_azureapicenter }}
