// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.iotoperationsmq.implementation;

import com.azure.core.http.rest.Response;
import com.azure.core.http.rest.SimpleResponse;
import com.azure.core.util.Context;
import com.azure.core.util.logging.ClientLogger;
import com.azure.resourcemanager.iotoperationsmq.fluent.OperationGroupsClient;
import com.azure.resourcemanager.iotoperationsmq.fluent.models.ResultInner;
import com.azure.resourcemanager.iotoperationsmq.models.OperationGroups;
import com.azure.resourcemanager.iotoperationsmq.models.Result;

public final class OperationGroupsImpl implements OperationGroups {
    private static final ClientLogger LOGGER = new ClientLogger(OperationGroupsImpl.class);

    private final OperationGroupsClient innerClient;

    private final com.azure.resourcemanager.iotoperationsmq.IotoperationsmqManager serviceManager;

    public OperationGroupsImpl(
        OperationGroupsClient innerClient,
        com.azure.resourcemanager.iotoperationsmq.IotoperationsmqManager serviceManager) {
        this.innerClient = innerClient;
        this.serviceManager = serviceManager;
    }

    public Response<Result> getWithResponse(String resourceGroupName, Context context) {
        Response<ResultInner> inner = this.serviceClient().getWithResponse(resourceGroupName, context);
        if (inner != null) {
            return new SimpleResponse<>(
                inner.getRequest(),
                inner.getStatusCode(),
                inner.getHeaders(),
                new ResultImpl(inner.getValue(), this.manager()));
        } else {
            return null;
        }
    }

    public Result get(String resourceGroupName) {
        ResultInner inner = this.serviceClient().get(resourceGroupName);
        if (inner != null) {
            return new ResultImpl(inner, this.manager());
        } else {
            return null;
        }
    }

    private OperationGroupsClient serviceClient() {
        return this.innerClient;
    }

    private com.azure.resourcemanager.iotoperationsmq.IotoperationsmqManager manager() {
        return this.serviceManager;
    }
}
