# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/scan/ci.yml
      - sdk/scan/azure-resourcemanager-scan/
    exclude:
      - sdk/scan/pom.xml
      - sdk/scan/azure-resourcemanager-scan/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/scan/ci.yml
      - sdk/scan/azure-resourcemanager-scan/
    exclude:
      - sdk/scan/pom.xml
      - sdk/scan/azure-resourcemanager-scan/pom.xml

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: scan
    Artifacts:
      - name: azure-resourcemanager-scan
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerscan
