// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.security.codetransparency.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The Response body of the GetOperationId API.
 */
@Immutable
public final class GetOperationResult {
    /*
     * ID of the transaction. Only if status is Succeeded.
     */
    @Generated
    @JsonProperty(value = "entryId")
    private String entryId;

    /*
     * Error in json format. Only if Status is Failed.
     */
    @Generated
    @JsonProperty(value = "error")
    private String error;

    /*
     * OperationId
     */
    @Generated
    @JsonProperty(value = "operationId")
    private String operationId;

    /*
     * Status of the operation.
     */
    @Generated
    @JsonProperty(value = "status")
    private OperationStatus status;

    /**
     * Creates an instance of GetOperationResult class.
     * 
     * @param operationId the operationId value to set.
     * @param status the status value to set.
     */
    @Generated
    @JsonCreator
    private GetOperationResult(@JsonProperty(value = "operationId") String operationId,
        @JsonProperty(value = "status") OperationStatus status) {
        this.operationId = operationId;
        this.status = status;
    }

    /**
     * Get the entryId property: ID of the transaction. Only if status is Succeeded.
     * 
     * @return the entryId value.
     */
    @Generated
    public String getEntryId() {
        return this.entryId;
    }

    /**
     * Get the error property: Error in json format. Only if Status is Failed.
     * 
     * @return the error value.
     */
    @Generated
    public String getError() {
        return this.error;
    }

    /**
     * Get the operationId property: OperationId.
     * 
     * @return the operationId value.
     */
    @Generated
    public String getOperationId() {
        return this.operationId;
    }

    /**
     * Get the status property: Status of the operation.
     * 
     * @return the status value.
     */
    @Generated
    public OperationStatus getStatus() {
        return this.status;
    }
}
