// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.scom.implementation;

import com.azure.resourcemanager.scom.fluent.models.LogAnalyticsConfigurationInner;
import com.azure.resourcemanager.scom.models.DataType;
import com.azure.resourcemanager.scom.models.LogAnalyticsConfiguration;
import java.util.Collections;
import java.util.List;

public final class LogAnalyticsConfigurationImpl implements LogAnalyticsConfiguration {
    private LogAnalyticsConfigurationInner innerObject;

    private final com.azure.resourcemanager.scom.ScomManager serviceManager;

    LogAnalyticsConfigurationImpl(LogAnalyticsConfigurationInner innerObject,
        com.azure.resourcemanager.scom.ScomManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String workspaceId() {
        return this.innerModel().workspaceId();
    }

    public List<DataType> dataTypes() {
        List<DataType> inner = this.innerModel().dataTypes();
        if (inner != null) {
            return Collections.unmodifiableList(inner);
        } else {
            return Collections.emptyList();
        }
    }

    public Boolean importData() {
        return this.innerModel().importData();
    }

    public LogAnalyticsConfigurationInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.scom.ScomManager manager() {
        return this.serviceManager;
    }
}
