# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/imageAnalysis/ci.yml
      - sdk/imageAnalysis/azure-ai-vision-imageanalysis/
    exclude:
      - sdk/imageAnalysis/pom.xml
      - sdk/imageAnalysis/azure-ai-vision-imageanalysis/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/imageAnalysis/ci.yml
      - sdk/imageAnalysis/azure-ai-vision-imageanalysis/
    exclude:
      - sdk/imageAnalysis/pom.xml
      - sdk/imageAnalysis/azure-ai-vision-imageanalysis/pom.xml

parameters:
  - name: release_azureaivisionimageanalysis
    displayName: azure-ai-vision-imageanalysis
    type: boolean
    default: true

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: imageAnalysis
    EnableBatchRelease: true
    Artifacts:
      - name: azure-ai-vision-imageanalysis
        groupId: com.azure
        safeName: azureaivisionimageanalysis
        releaseInBatch: ${{ parameters.release_azureaivisionimageanalysis }}
