# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/windfall/ci.yml
      - sdk/windfall/azure-resourcemanager-windfall/
    exclude:
      - sdk/windfall/pom.xml
      - sdk/windfall/azure-resourcemanager-windfall/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/windfall/ci.yml
      - sdk/windfall/azure-resourcemanager-windfall/
    exclude:
      - sdk/windfall/pom.xml
      - sdk/windfall/azure-resourcemanager-windfall/pom.xml

parameters:
  - name: release_azureresourcemanagerwindfall
    displayName: azure-resourcemanager-windfall
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: windfall
    EnableBatchRelease: true
    Artifacts:
      - name: azure-resourcemanager-windfall
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerwindfall
        releaseInBatch: ${{ parameters.release_azureresourcemanagerwindfall }}
