# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/workloadmonitor/ci.yml
      - sdk/workloadmonitor/azure-resourcemanager-workloadmonitor/
    exclude:
      - sdk/workloadmonitor/pom.xml
      - sdk/workloadmonitor/azure-resourcemanager-workloadmonitor/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/workloadmonitor/ci.yml
      - sdk/workloadmonitor/azure-resourcemanager-workloadmonitor/
    exclude:
      - sdk/workloadmonitor/pom.xml
      - sdk/workloadmonitor/azure-resourcemanager-workloadmonitor/pom.xml

parameters:
  - name: release_azureresourcemanagerworkloadmonitor
    displayName: azure-resourcemanager-workloadmonitor
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: workloadmonitor
    EnableBatchRelease: true
    Artifacts:
      - name: azure-resourcemanager-workloadmonitor
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerworkloadmonitor
        releaseInBatch: ${{ parameters.release_azureresourcemanagerworkloadmonitor }}
