# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/containerserviceaks/ci.yml
      - sdk/containerserviceaks/azure-resourcemanager-containerserviceaks-generated/
    exclude:
      - sdk/containerserviceaks/pom.xml
      - sdk/containerserviceaks/azure-resourcemanager-containerserviceaks-generated/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/containerserviceaks/ci.yml
      - sdk/containerserviceaks/azure-resourcemanager-containerserviceaks-generated/
    exclude:
      - sdk/containerserviceaks/pom.xml
      - sdk/containerserviceaks/azure-resourcemanager-containerserviceaks-generated/pom.xml

parameters:
  - name: release_azureresourcemanagercontainerserviceaksgenerated
    displayName: azure-resourcemanager-containerserviceaks-generated
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: containerserviceaks
    Artifacts:
      - name: azure-resourcemanager-containerserviceaks-generated
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagercontainerserviceaksgenerated
        releaseInBatch: ${{ parameters.release_azureresourcemanagercontainerserviceaksgenerated }}
