# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/informatica/ci.yml
      - sdk/informatica/azure-resourcemanager-informatica/
    exclude:
      - sdk/informatica/pom.xml
      - sdk/informatica/azure-resourcemanager-informatica/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/informatica/ci.yml
      - sdk/informatica/azure-resourcemanager-informatica/
    exclude:
      - sdk/informatica/pom.xml
      - sdk/informatica/azure-resourcemanager-informatica/pom.xml

parameters:
  - name: release_azureresourcemanagerinformatica
    displayName: azure-resourcemanager-informatica
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: informatica
    EnableBatchRelease: true
    Artifacts:
      - name: azure-resourcemanager-informatica
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerinformatica
        releaseInBatch: ${{ parameters.release_azureresourcemanagerinformatica }}
