// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.datamigration.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/** Database Migration Resource properties for SQL Virtual Machine. */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("SqlVm")
@Fluent
public final class DatabaseMigrationPropertiesSqlVm extends DatabaseMigrationProperties {
    /*
     * Detailed migration status. Not included by default.
     */
    @JsonProperty(value = "migrationStatusDetails", access = JsonProperty.Access.WRITE_ONLY)
    private MigrationStatusDetails migrationStatusDetails;

    /*
     * Database collation to be used for the target database.
     */
    @JsonProperty(value = "targetDatabaseCollation")
    private String targetDatabaseCollation;

    /*
     * Error message for migration provisioning failure, if any.
     */
    @JsonProperty(value = "provisioningError")
    private String provisioningError;

    /*
     * Backup configuration info.
     */
    @JsonProperty(value = "backupConfiguration")
    private BackupConfiguration backupConfiguration;

    /*
     * Offline configuration.
     */
    @JsonProperty(value = "offlineConfiguration")
    private OfflineConfiguration offlineConfiguration;

    /** Creates an instance of DatabaseMigrationPropertiesSqlVm class. */
    public DatabaseMigrationPropertiesSqlVm() {
    }

    /**
     * Get the migrationStatusDetails property: Detailed migration status. Not included by default.
     *
     * @return the migrationStatusDetails value.
     */
    public MigrationStatusDetails migrationStatusDetails() {
        return this.migrationStatusDetails;
    }

    /**
     * Get the targetDatabaseCollation property: Database collation to be used for the target database.
     *
     * @return the targetDatabaseCollation value.
     */
    public String targetDatabaseCollation() {
        return this.targetDatabaseCollation;
    }

    /**
     * Set the targetDatabaseCollation property: Database collation to be used for the target database.
     *
     * @param targetDatabaseCollation the targetDatabaseCollation value to set.
     * @return the DatabaseMigrationPropertiesSqlVm object itself.
     */
    public DatabaseMigrationPropertiesSqlVm withTargetDatabaseCollation(String targetDatabaseCollation) {
        this.targetDatabaseCollation = targetDatabaseCollation;
        return this;
    }

    /**
     * Get the provisioningError property: Error message for migration provisioning failure, if any.
     *
     * @return the provisioningError value.
     */
    public String provisioningError() {
        return this.provisioningError;
    }

    /**
     * Set the provisioningError property: Error message for migration provisioning failure, if any.
     *
     * @param provisioningError the provisioningError value to set.
     * @return the DatabaseMigrationPropertiesSqlVm object itself.
     */
    public DatabaseMigrationPropertiesSqlVm withProvisioningError(String provisioningError) {
        this.provisioningError = provisioningError;
        return this;
    }

    /**
     * Get the backupConfiguration property: Backup configuration info.
     *
     * @return the backupConfiguration value.
     */
    public BackupConfiguration backupConfiguration() {
        return this.backupConfiguration;
    }

    /**
     * Set the backupConfiguration property: Backup configuration info.
     *
     * @param backupConfiguration the backupConfiguration value to set.
     * @return the DatabaseMigrationPropertiesSqlVm object itself.
     */
    public DatabaseMigrationPropertiesSqlVm withBackupConfiguration(BackupConfiguration backupConfiguration) {
        this.backupConfiguration = backupConfiguration;
        return this;
    }

    /**
     * Get the offlineConfiguration property: Offline configuration.
     *
     * @return the offlineConfiguration value.
     */
    public OfflineConfiguration offlineConfiguration() {
        return this.offlineConfiguration;
    }

    /**
     * Set the offlineConfiguration property: Offline configuration.
     *
     * @param offlineConfiguration the offlineConfiguration value to set.
     * @return the DatabaseMigrationPropertiesSqlVm object itself.
     */
    public DatabaseMigrationPropertiesSqlVm withOfflineConfiguration(OfflineConfiguration offlineConfiguration) {
        this.offlineConfiguration = offlineConfiguration;
        return this;
    }

    /** {@inheritDoc} */
    @Override
    public DatabaseMigrationPropertiesSqlVm withScope(String scope) {
        super.withScope(scope);
        return this;
    }

    /** {@inheritDoc} */
    @Override
    public DatabaseMigrationPropertiesSqlVm withSourceSqlConnection(SqlConnectionInformation sourceSqlConnection) {
        super.withSourceSqlConnection(sourceSqlConnection);
        return this;
    }

    /** {@inheritDoc} */
    @Override
    public DatabaseMigrationPropertiesSqlVm withSourceDatabaseName(String sourceDatabaseName) {
        super.withSourceDatabaseName(sourceDatabaseName);
        return this;
    }

    /** {@inheritDoc} */
    @Override
    public DatabaseMigrationPropertiesSqlVm withMigrationService(String migrationService) {
        super.withMigrationService(migrationService);
        return this;
    }

    /** {@inheritDoc} */
    @Override
    public DatabaseMigrationPropertiesSqlVm withMigrationOperationId(String migrationOperationId) {
        super.withMigrationOperationId(migrationOperationId);
        return this;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    @Override
    public void validate() {
        super.validate();
        if (migrationStatusDetails() != null) {
            migrationStatusDetails().validate();
        }
        if (backupConfiguration() != null) {
            backupConfiguration().validate();
        }
        if (offlineConfiguration() != null) {
            offlineConfiguration().validate();
        }
    }
}
