# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/kubernetesconfigurationmicrosoftkubernetesconfigurationextensions/ci.yml
      - sdk/kubernetesconfigurationmicrosoftkubernetesconfigurationextensions/azure-resourcemanager-kubernetesconfigurationmicrosoftkubernetesconfigurationextensions/
    exclude:
      - sdk/kubernetesconfigurationmicrosoftkubernetesconfigurationextensions/pom.xml
      - sdk/kubernetesconfigurationmicrosoftkubernetesconfigurationextensions/azure-resourcemanager-kubernetesconfigurationmicrosoftkubernetesconfigurationextensions/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/kubernetesconfigurationmicrosoftkubernetesconfigurationextensions/ci.yml
      - sdk/kubernetesconfigurationmicrosoftkubernetesconfigurationextensions/azure-resourcemanager-kubernetesconfigurationmicrosoftkubernetesconfigurationextensions/
    exclude:
      - sdk/kubernetesconfigurationmicrosoftkubernetesconfigurationextensions/pom.xml
      - sdk/kubernetesconfigurationmicrosoftkubernetesconfigurationextensions/azure-resourcemanager-kubernetesconfigurationmicrosoftkubernetesconfigurationextensions/pom.xml

parameters:
  - name: release_azureresourcemanagerkubernetesconfigurationmicrosoftkubernetesconfigurationextensions
    displayName: azure-resourcemanager-kubernetesconfigurationmicrosoftkubernetesconfigurationextensions
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: kubernetesconfigurationmicrosoftkubernetesconfigurationextensions
    Artifacts:
      - name: azure-resourcemanager-kubernetesconfigurationmicrosoftkubernetesconfigurationextensions
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerkubernetesconfigurationmicrosoftkubernetesconfigurationextensions
        releaseInBatch: ${{ parameters.release_azureresourcemanagerkubernetesconfigurationmicrosoftkubernetesconfigurationextensions }}
