// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.appconfiguration.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * Properties of a network security perimeter provisioning issue.
 */
@Immutable
public final class NspProvisioningIssueProperties {
    /*
     * The type of provisioning issue
     */
    @JsonProperty(value = "issueType", access = JsonProperty.Access.WRITE_ONLY)
    private NspProvisioningIssueType issueType;

    /*
     * The severity of the provisioning issue
     */
    @JsonProperty(value = "severity", access = JsonProperty.Access.WRITE_ONLY)
    private NspProvisioningIssueSeverity severity;

    /*
     * The description of the provisioning issue
     */
    @JsonProperty(value = "description", access = JsonProperty.Access.WRITE_ONLY)
    private String description;

    /*
     * List of IDs of Azure resources that can be associated to the same perimeter to remediate the issue
     */
    @JsonProperty(value = "suggestedResourceIds", access = JsonProperty.Access.WRITE_ONLY)
    private List<String> suggestedResourceIds;

    /*
     * Access rules that can be added to the perimeter to remediate the issue
     */
    @JsonProperty(value = "suggestedAccessRules", access = JsonProperty.Access.WRITE_ONLY)
    private List<NspProfileAccessRule> suggestedAccessRules;

    /**
     * Creates an instance of NspProvisioningIssueProperties class.
     */
    public NspProvisioningIssueProperties() {
    }

    /**
     * Get the issueType property: The type of provisioning issue.
     * 
     * @return the issueType value.
     */
    public NspProvisioningIssueType issueType() {
        return this.issueType;
    }

    /**
     * Get the severity property: The severity of the provisioning issue.
     * 
     * @return the severity value.
     */
    public NspProvisioningIssueSeverity severity() {
        return this.severity;
    }

    /**
     * Get the description property: The description of the provisioning issue.
     * 
     * @return the description value.
     */
    public String description() {
        return this.description;
    }

    /**
     * Get the suggestedResourceIds property: List of IDs of Azure resources that can be associated to the same
     * perimeter to remediate the issue.
     * 
     * @return the suggestedResourceIds value.
     */
    public List<String> suggestedResourceIds() {
        return this.suggestedResourceIds;
    }

    /**
     * Get the suggestedAccessRules property: Access rules that can be added to the perimeter to remediate the issue.
     * 
     * @return the suggestedAccessRules value.
     */
    public List<NspProfileAccessRule> suggestedAccessRules() {
        return this.suggestedAccessRules;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (suggestedAccessRules() != null) {
            suggestedAccessRules().forEach(e -> e.validate());
        }
    }
}
