# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/azurestackhcimicrosoftazurestackhcistackhci/ci.yml
      - sdk/azurestackhcimicrosoftazurestackhcistackhci/azure-resourcemanager-azurestackhcimicrosoftazurestackhcistackhci/
    exclude:
      - sdk/azurestackhcimicrosoftazurestackhcistackhci/pom.xml
      - sdk/azurestackhcimicrosoftazurestackhcistackhci/azure-resourcemanager-azurestackhcimicrosoftazurestackhcistackhci/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/azurestackhcimicrosoftazurestackhcistackhci/ci.yml
      - sdk/azurestackhcimicrosoftazurestackhcistackhci/azure-resourcemanager-azurestackhcimicrosoftazurestackhcistackhci/
    exclude:
      - sdk/azurestackhcimicrosoftazurestackhcistackhci/pom.xml
      - sdk/azurestackhcimicrosoftazurestackhcistackhci/azure-resourcemanager-azurestackhcimicrosoftazurestackhcistackhci/pom.xml

parameters:
  - name: release_azureresourcemanagerazurestackhcimicrosoftazurestackhcistackhci
    displayName: azure-resourcemanager-azurestackhcimicrosoftazurestackhcistackhci
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: azurestackhcimicrosoftazurestackhcistackhci
    EnableBatchRelease: true
    Artifacts:
      - name: azure-resourcemanager-azurestackhcimicrosoftazurestackhcistackhci
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerazurestackhcimicrosoftazurestackhcistackhci
        releaseInBatch: ${{ parameters.release_azureresourcemanagerazurestackhcimicrosoftazurestackhcistackhci }}
