// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.synapse.models;

import com.azure.resourcemanager.synapse.fluent.models.IntergrationruntimesOperationStatusInner;

/** An immutable client-side representation of IntergrationruntimesOperationStatus. */
public interface IntergrationruntimesOperationStatus {
    /**
     * Gets the id property: Fully qualified resource Id for the resource.
     *
     * @return the id value.
     */
    String id();

    /**
     * Gets the name property: The name of the resource.
     *
     * @return the name value.
     */
    String name();

    /**
     * Gets the type property: The type of the resource.
     *
     * @return the type value.
     */
    String type();

    /**
     * Gets the location property: The geo-location where the resource lives.
     *
     * @return the location value.
     */
    String location();

    /**
     * Gets the status property: status of stop Integrationruntimes.
     *
     * @return the status value.
     */
    WorkspaceStatus status();

    /**
     * Gets the namePropertiesName property: Name of Operation Statuses.
     *
     * @return the namePropertiesName value.
     */
    String namePropertiesName();

    /**
     * Gets the properties property: properties value for 8A2431BC39114B709A447C12F99E3BB4.
     *
     * @return the properties value.
     */
    String properties();

    /**
     * Gets the error property: error value for 8A2431BC39114B709A447C12F99E3BB4.
     *
     * @return the error value.
     */
    String error();

    /**
     * Gets the inner com.azure.resourcemanager.synapse.fluent.models.IntergrationruntimesOperationStatusInner object.
     *
     * @return the inner object.
     */
    IntergrationruntimesOperationStatusInner innerModel();
}
