# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/dell/ci.yml
      - sdk/dell/azure-resourcemanager-dell/
    exclude:
      - sdk/dell/pom.xml
      - sdk/dell/azure-resourcemanager-dell/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/dell/ci.yml
      - sdk/dell/azure-resourcemanager-dell/
    exclude:
      - sdk/dell/pom.xml
      - sdk/dell/azure-resourcemanager-dell/pom.xml

parameters:
  - name: release_azureresourcemanagerdell
    displayName: azure-resourcemanager-dell
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: dell
    Artifacts:
      - name: azure-resourcemanager-dell
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerdell
        releaseInBatch: ${{ parameters.release_azureresourcemanagerdell }}
