# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/playwright/ci.yml
      - sdk/playwright/azure-developer-playwright/
    exclude:
      - sdk/playwright/pom.xml
      - sdk/playwright/azure-developer-playwright/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/playwright/ci.yml
      - sdk/playwright/azure-developer-playwright/
    exclude:
      - sdk/playwright/pom.xml
      - sdk/playwright/azure-developer-playwright/pom.xml

parameters:
  - name: release_azuredeveloperplaywright
    displayName: azure-developer-playwright
    type: boolean
    default: true

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: playwright
    Artifacts:
      - name: azure-developer-playwright
        groupId: com.azure
        safeName: azuredeveloperplaywright
        releaseInBatch: ${{ parameters.release_azuredeveloperplaywright }}
