// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.billingbenefits.models;

import com.azure.resourcemanager.billingbenefits.fluent.models.SavingsPlanUpdateRequestInner;

/** An immutable client-side representation of SavingsPlanUpdateRequest. */
public interface SavingsPlanUpdateRequest {
    /**
     * Gets the properties property: Savings plan patch request.
     *
     * @return the properties value.
     */
    SavingsPlanUpdateRequestProperties properties();

    /**
     * Gets the inner com.azure.resourcemanager.billingbenefits.fluent.models.SavingsPlanUpdateRequestInner object.
     *
     * @return the inner object.
     */
    SavingsPlanUpdateRequestInner innerModel();
}
