# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/cosmosdbmicrosoftdocumentdbcore/ci.yml
      - sdk/cosmosdbmicrosoftdocumentdbcore/azure-resourcemanager-cosmosdbmicrosoftdocumentdbcore/
    exclude:
      - sdk/cosmosdbmicrosoftdocumentdbcore/pom.xml
      - sdk/cosmosdbmicrosoftdocumentdbcore/azure-resourcemanager-cosmosdbmicrosoftdocumentdbcore/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/cosmosdbmicrosoftdocumentdbcore/ci.yml
      - sdk/cosmosdbmicrosoftdocumentdbcore/azure-resourcemanager-cosmosdbmicrosoftdocumentdbcore/
    exclude:
      - sdk/cosmosdbmicrosoftdocumentdbcore/pom.xml
      - sdk/cosmosdbmicrosoftdocumentdbcore/azure-resourcemanager-cosmosdbmicrosoftdocumentdbcore/pom.xml

parameters:
  - name: release_azureresourcemanagercosmosdbmicrosoftdocumentdbcore
    displayName: azure-resourcemanager-cosmosdbmicrosoftdocumentdbcore
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: cosmosdbmicrosoftdocumentdbcore
    EnableBatchRelease: true
    Artifacts:
      - name: azure-resourcemanager-cosmosdbmicrosoftdocumentdbcore
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagercosmosdbmicrosoftdocumentdbcore
        releaseInBatch: ${{ parameters.release_azureresourcemanagercosmosdbmicrosoftdocumentdbcore }}
