# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/carbonoptimization/ci.yml
      - sdk/carbonoptimization/azure-mgmt-carbonoptimization/
    exclude:
      - sdk/carbonoptimization/pom.xml
      - sdk/carbonoptimization/azure-mgmt-carbonoptimization/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/carbonoptimization/ci.yml
      - sdk/carbonoptimization/azure-mgmt-carbonoptimization/
    exclude:
      - sdk/carbonoptimization/pom.xml
      - sdk/carbonoptimization/azure-mgmt-carbonoptimization/pom.xml

parameters:
  - name: release_azuremgmtcarbonoptimization
    displayName: azure-mgmt-carbonoptimization
    type: boolean
    default: true

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: carbonoptimization
    Artifacts:
      - name: azure-mgmt-carbonoptimization
        groupId: com.azure.resourcemanager
        safeName: azuremgmtcarbonoptimization
        releaseInBatch: ${{ parameters.release_azuremgmtcarbonoptimization }}
