# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/engagementfabric/ci.yml
      - sdk/engagementfabric/azure-resourcemanager-engagementfabric/
    exclude:
      - sdk/engagementfabric/pom.xml
      - sdk/engagementfabric/azure-resourcemanager-engagementfabric/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/engagementfabric/ci.yml
      - sdk/engagementfabric/azure-resourcemanager-engagementfabric/
    exclude:
      - sdk/engagementfabric/pom.xml
      - sdk/engagementfabric/azure-resourcemanager-engagementfabric/pom.xml

parameters:
  - name: release_azureresourcemanagerengagementfabric
    displayName: azure-resourcemanager-engagementfabric
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: engagementfabric
    EnableBatchRelease: true
    Artifacts:
      - name: azure-resourcemanager-engagementfabric
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerengagementfabric
        releaseInBatch: ${{ parameters.release_azureresourcemanagerengagementfabric }}
