# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/customproviders/ci.yml
      - sdk/customproviders/azure-resourcemanager-customproviders/
    exclude:
      - sdk/customproviders/pom.xml
      - sdk/customproviders/azure-resourcemanager-customproviders/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/customproviders/ci.yml
      - sdk/customproviders/azure-resourcemanager-customproviders/
    exclude:
      - sdk/customproviders/pom.xml
      - sdk/customproviders/azure-resourcemanager-customproviders/pom.xml

parameters:
  - name: release_azureresourcemanagercustomproviders
    displayName: azure-resourcemanager-customproviders
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: customproviders
    Artifacts:
      - name: azure-resourcemanager-customproviders
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagercustomproviders
        releaseInBatch: ${{ parameters.release_azureresourcemanagercustomproviders }}
