// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.awsconnector.models;

import com.azure.core.util.ExpandableStringEnum;
import java.util.Collection;

/**
 * AccessControl enum.
 */
public final class AccessControl extends ExpandableStringEnum<AccessControl> {
    /**
     * Static value AuthenticatedRead for AccessControl.
     */
    public static final AccessControl AUTHENTICATED_READ = fromString("AuthenticatedRead");

    /**
     * Static value AwsExecRead for AccessControl.
     */
    public static final AccessControl AWS_EXEC_READ = fromString("AwsExecRead");

    /**
     * Static value BucketOwnerFullControl for AccessControl.
     */
    public static final AccessControl BUCKET_OWNER_FULL_CONTROL = fromString("BucketOwnerFullControl");

    /**
     * Static value BucketOwnerRead for AccessControl.
     */
    public static final AccessControl BUCKET_OWNER_READ = fromString("BucketOwnerRead");

    /**
     * Static value LogDeliveryWrite for AccessControl.
     */
    public static final AccessControl LOG_DELIVERY_WRITE = fromString("LogDeliveryWrite");

    /**
     * Static value Private for AccessControl.
     */
    public static final AccessControl PRIVATE = fromString("Private");

    /**
     * Static value PublicRead for AccessControl.
     */
    public static final AccessControl PUBLIC_READ = fromString("PublicRead");

    /**
     * Static value PublicReadWrite for AccessControl.
     */
    public static final AccessControl PUBLIC_READ_WRITE = fromString("PublicReadWrite");

    /**
     * Creates a new instance of AccessControl value.
     * 
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Deprecated
    public AccessControl() {
    }

    /**
     * Creates or finds a AccessControl from its string representation.
     * 
     * @param name a name to look for.
     * @return the corresponding AccessControl.
     */
    public static AccessControl fromString(String name) {
        return fromString(name, AccessControl.class);
    }

    /**
     * Gets known AccessControl values.
     * 
     * @return known AccessControl values.
     */
    public static Collection<AccessControl> values() {
        return values(AccessControl.class);
    }
}
