// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.awsconnector.models;

import com.azure.core.http.rest.PagedIterable;
import com.azure.core.http.rest.Response;
import com.azure.core.util.Context;

/**
 * Resource collection API of NetworkFirewallRuleGroups.
 */
public interface NetworkFirewallRuleGroups {
    /**
     * List NetworkFirewallRuleGroup resources by subscription ID.
     * 
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response of a NetworkFirewallRuleGroup list operation as paginated response with
     * {@link PagedIterable}.
     */
    PagedIterable<NetworkFirewallRuleGroup> list();

    /**
     * List NetworkFirewallRuleGroup resources by subscription ID.
     * 
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response of a NetworkFirewallRuleGroup list operation as paginated response with
     * {@link PagedIterable}.
     */
    PagedIterable<NetworkFirewallRuleGroup> list(Context context);

    /**
     * List NetworkFirewallRuleGroup resources by resource group.
     * 
     * @param resourceGroupName The name of the resource group. The name is case insensitive.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response of a NetworkFirewallRuleGroup list operation as paginated response with
     * {@link PagedIterable}.
     */
    PagedIterable<NetworkFirewallRuleGroup> listByResourceGroup(String resourceGroupName);

    /**
     * List NetworkFirewallRuleGroup resources by resource group.
     * 
     * @param resourceGroupName The name of the resource group. The name is case insensitive.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response of a NetworkFirewallRuleGroup list operation as paginated response with
     * {@link PagedIterable}.
     */
    PagedIterable<NetworkFirewallRuleGroup> listByResourceGroup(String resourceGroupName, Context context);

    /**
     * Get a NetworkFirewallRuleGroup.
     * 
     * @param resourceGroupName The name of the resource group. The name is case insensitive.
     * @param name Name of NetworkFirewallRuleGroup.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return a NetworkFirewallRuleGroup along with {@link Response}.
     */
    Response<NetworkFirewallRuleGroup> getByResourceGroupWithResponse(String resourceGroupName, String name,
        Context context);

    /**
     * Get a NetworkFirewallRuleGroup.
     * 
     * @param resourceGroupName The name of the resource group. The name is case insensitive.
     * @param name Name of NetworkFirewallRuleGroup.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return a NetworkFirewallRuleGroup.
     */
    NetworkFirewallRuleGroup getByResourceGroup(String resourceGroupName, String name);

    /**
     * Delete a NetworkFirewallRuleGroup.
     * 
     * @param resourceGroupName The name of the resource group. The name is case insensitive.
     * @param name Name of NetworkFirewallRuleGroup.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    void deleteByResourceGroup(String resourceGroupName, String name);

    /**
     * Delete a NetworkFirewallRuleGroup.
     * 
     * @param resourceGroupName The name of the resource group. The name is case insensitive.
     * @param name Name of NetworkFirewallRuleGroup.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    void delete(String resourceGroupName, String name, Context context);

    /**
     * Get a NetworkFirewallRuleGroup.
     * 
     * @param id the resource ID.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return a NetworkFirewallRuleGroup along with {@link Response}.
     */
    NetworkFirewallRuleGroup getById(String id);

    /**
     * Get a NetworkFirewallRuleGroup.
     * 
     * @param id the resource ID.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return a NetworkFirewallRuleGroup along with {@link Response}.
     */
    Response<NetworkFirewallRuleGroup> getByIdWithResponse(String id, Context context);

    /**
     * Delete a NetworkFirewallRuleGroup.
     * 
     * @param id the resource ID.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    void deleteById(String id);

    /**
     * Delete a NetworkFirewallRuleGroup.
     * 
     * @param id the resource ID.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    void deleteByIdWithResponse(String id, Context context);

    /**
     * Begins definition for a new NetworkFirewallRuleGroup resource.
     * 
     * @param name resource name.
     * @return the first stage of the new NetworkFirewallRuleGroup definition.
     */
    NetworkFirewallRuleGroup.DefinitionStages.Blank define(String name);
}
