// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.awsconnector.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.util.logging.ClientLogger;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import com.azure.resourcemanager.awsconnector.fluent.models.S3AccessPointInner;
import java.io.IOException;
import java.util.List;

/**
 * The response of a S3AccessPoint list operation.
 */
@Fluent
public final class S3AccessPointListResult implements JsonSerializable<S3AccessPointListResult> {
    /*
     * The S3AccessPoint items on this page
     */
    private List<S3AccessPointInner> value;

    /*
     * The link to the next page of items
     */
    private String nextLink;

    /**
     * Creates an instance of S3AccessPointListResult class.
     */
    public S3AccessPointListResult() {
    }

    /**
     * Get the value property: The S3AccessPoint items on this page.
     * 
     * @return the value value.
     */
    public List<S3AccessPointInner> value() {
        return this.value;
    }

    /**
     * Set the value property: The S3AccessPoint items on this page.
     * 
     * @param value the value value to set.
     * @return the S3AccessPointListResult object itself.
     */
    public S3AccessPointListResult withValue(List<S3AccessPointInner> value) {
        this.value = value;
        return this;
    }

    /**
     * Get the nextLink property: The link to the next page of items.
     * 
     * @return the nextLink value.
     */
    public String nextLink() {
        return this.nextLink;
    }

    /**
     * Set the nextLink property: The link to the next page of items.
     * 
     * @param nextLink the nextLink value to set.
     * @return the S3AccessPointListResult object itself.
     */
    public S3AccessPointListResult withNextLink(String nextLink) {
        this.nextLink = nextLink;
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (value() == null) {
            throw LOGGER.atError()
                .log(new IllegalArgumentException("Missing required property value in model S3AccessPointListResult"));
        } else {
            value().forEach(e -> e.validate());
        }
    }

    private static final ClientLogger LOGGER = new ClientLogger(S3AccessPointListResult.class);

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeArrayField("value", this.value, (writer, element) -> writer.writeJson(element));
        jsonWriter.writeStringField("nextLink", this.nextLink);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of S3AccessPointListResult from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of S3AccessPointListResult if the JsonReader was pointing to an instance of it, or null if it
     * was pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the S3AccessPointListResult.
     */
    public static S3AccessPointListResult fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            S3AccessPointListResult deserializedS3AccessPointListResult = new S3AccessPointListResult();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("value".equals(fieldName)) {
                    List<S3AccessPointInner> value = reader.readArray(reader1 -> S3AccessPointInner.fromJson(reader1));
                    deserializedS3AccessPointListResult.value = value;
                } else if ("nextLink".equals(fieldName)) {
                    deserializedS3AccessPointListResult.nextLink = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedS3AccessPointListResult;
        });
    }
}
