// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.awsconnector.models;

import com.azure.core.annotation.Fluent;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;

/**
 * Definition of VpcSecurityGroupMembership.
 */
@Fluent
public final class VpcSecurityGroupMembership implements JsonSerializable<VpcSecurityGroupMembership> {
    /*
     * <p>The status of the VPC security group.</p>
     */
    private String status;

    /*
     * <p>The VPC security group ID.</p>
     */
    private String vpcSecurityGroupId;

    /**
     * Creates an instance of VpcSecurityGroupMembership class.
     */
    public VpcSecurityGroupMembership() {
    }

    /**
     * Get the status property: &lt;p&gt;The status of the VPC security group.&lt;/p&gt;.
     * 
     * @return the status value.
     */
    public String status() {
        return this.status;
    }

    /**
     * Set the status property: &lt;p&gt;The status of the VPC security group.&lt;/p&gt;.
     * 
     * @param status the status value to set.
     * @return the VpcSecurityGroupMembership object itself.
     */
    public VpcSecurityGroupMembership withStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * Get the vpcSecurityGroupId property: &lt;p&gt;The VPC security group ID.&lt;/p&gt;.
     * 
     * @return the vpcSecurityGroupId value.
     */
    public String vpcSecurityGroupId() {
        return this.vpcSecurityGroupId;
    }

    /**
     * Set the vpcSecurityGroupId property: &lt;p&gt;The VPC security group ID.&lt;/p&gt;.
     * 
     * @param vpcSecurityGroupId the vpcSecurityGroupId value to set.
     * @return the VpcSecurityGroupMembership object itself.
     */
    public VpcSecurityGroupMembership withVpcSecurityGroupId(String vpcSecurityGroupId) {
        this.vpcSecurityGroupId = vpcSecurityGroupId;
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("status", this.status);
        jsonWriter.writeStringField("vpcSecurityGroupId", this.vpcSecurityGroupId);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of VpcSecurityGroupMembership from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of VpcSecurityGroupMembership if the JsonReader was pointing to an instance of it, or null if
     * it was pointing to JSON null.
     * @throws IOException If an error occurs while reading the VpcSecurityGroupMembership.
     */
    public static VpcSecurityGroupMembership fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            VpcSecurityGroupMembership deserializedVpcSecurityGroupMembership = new VpcSecurityGroupMembership();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("status".equals(fieldName)) {
                    deserializedVpcSecurityGroupMembership.status = reader.getString();
                } else if ("vpcSecurityGroupId".equals(fieldName)) {
                    deserializedVpcSecurityGroupMembership.vpcSecurityGroupId = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedVpcSecurityGroupMembership;
        });
    }
}
