# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/testbase/ci.yml
      - sdk/testbase/azure-resourcemanager-testbase/
    exclude:
      - sdk/testbase/pom.xml
      - sdk/testbase/azure-resourcemanager-testbase/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/testbase/ci.yml
      - sdk/testbase/azure-resourcemanager-testbase/
    exclude:
      - sdk/testbase/pom.xml
      - sdk/testbase/azure-resourcemanager-testbase/pom.xml

parameters:
  - name: release_azureresourcemanagertestbase
    displayName: azure-resourcemanager-testbase
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: testbase
    EnableBatchRelease: true
    Artifacts:
      - name: azure-resourcemanager-testbase
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagertestbase
        releaseInBatch: ${{ parameters.release_azureresourcemanagertestbase }}
