# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/fairfieldgardens/ci.yml
      - sdk/fairfieldgardens/azure-resourcemanager-fairfieldgardens/
    exclude:
      - sdk/fairfieldgardens/pom.xml
      - sdk/fairfieldgardens/azure-resourcemanager-fairfieldgardens/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/fairfieldgardens/ci.yml
      - sdk/fairfieldgardens/azure-resourcemanager-fairfieldgardens/
    exclude:
      - sdk/fairfieldgardens/pom.xml
      - sdk/fairfieldgardens/azure-resourcemanager-fairfieldgardens/pom.xml

parameters:
  - name: release_azureresourcemanagerfairfieldgardens
    displayName: azure-resourcemanager-fairfieldgardens
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: fairfieldgardens
    EnableBatchRelease: true
    Artifacts:
      - name: azure-resourcemanager-fairfieldgardens
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerfairfieldgardens
        releaseInBatch: ${{ parameters.release_azureresourcemanagerfairfieldgardens }}
