# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/premonition/ci.yml
      - sdk/premonition/azure-resourcemanager-premonition/
    exclude:
      - sdk/premonition/pom.xml
      - sdk/premonition/azure-resourcemanager-premonition/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/premonition/ci.yml
      - sdk/premonition/azure-resourcemanager-premonition/
    exclude:
      - sdk/premonition/pom.xml
      - sdk/premonition/azure-resourcemanager-premonition/pom.xml

parameters:
  - name: release_azureresourcemanagerpremonition
    displayName: azure-resourcemanager-premonition
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: premonition
    Artifacts:
      - name: azure-resourcemanager-premonition
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerpremonition
        releaseInBatch: ${{ parameters.release_azureresourcemanagerpremonition }}
