# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/agricultureplatform/ci.yml
      - sdk/agricultureplatform/azure-resourcemanager-agricultureplatform/
    exclude:
      - sdk/agricultureplatform/pom.xml
      - sdk/agricultureplatform/azure-resourcemanager-agricultureplatform/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/agricultureplatform/ci.yml
      - sdk/agricultureplatform/azure-resourcemanager-agricultureplatform/
    exclude:
      - sdk/agricultureplatform/pom.xml
      - sdk/agricultureplatform/azure-resourcemanager-agricultureplatform/pom.xml

parameters:
  - name: release_azureresourcemanageragricultureplatform
    displayName: azure-resourcemanager-agricultureplatform
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: agricultureplatform
    Artifacts:
      - name: azure-resourcemanager-agricultureplatform
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanageragricultureplatform
        releaseInBatch: ${{ parameters.release_azureresourcemanageragricultureplatform }}
