# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/managednetwork/ci.yml
      - sdk/managednetwork/azure-resourcemanager-managednetwork/
    exclude:
      - sdk/managednetwork/pom.xml
      - sdk/managednetwork/azure-resourcemanager-managednetwork/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/managednetwork/ci.yml
      - sdk/managednetwork/azure-resourcemanager-managednetwork/
    exclude:
      - sdk/managednetwork/pom.xml
      - sdk/managednetwork/azure-resourcemanager-managednetwork/pom.xml

parameters:
  - name: release_azureresourcemanagermanagednetwork
    displayName: azure-resourcemanager-managednetwork
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: managednetwork
    EnableBatchRelease: true
    Artifacts:
      - name: azure-resourcemanager-managednetwork
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagermanagednetwork
        releaseInBatch: ${{ parameters.release_azureresourcemanagermanagednetwork }}
