// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.avs.models;

import com.azure.core.util.ExpandableStringEnum;
import java.util.Collection;

/**
 * provisioning state of the maintenance.
 */
public final class MaintenanceProvisioningState extends ExpandableStringEnum<MaintenanceProvisioningState> {
    /**
     * Static value Succeeded for MaintenanceProvisioningState.
     */
    public static final MaintenanceProvisioningState SUCCEEDED = fromString("Succeeded");

    /**
     * Static value Failed for MaintenanceProvisioningState.
     */
    public static final MaintenanceProvisioningState FAILED = fromString("Failed");

    /**
     * Static value Canceled for MaintenanceProvisioningState.
     */
    public static final MaintenanceProvisioningState CANCELED = fromString("Canceled");

    /**
     * Static value Updating for MaintenanceProvisioningState.
     */
    public static final MaintenanceProvisioningState UPDATING = fromString("Updating");

    /**
     * Creates a new instance of MaintenanceProvisioningState value.
     * 
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Deprecated
    public MaintenanceProvisioningState() {
    }

    /**
     * Creates or finds a MaintenanceProvisioningState from its string representation.
     * 
     * @param name a name to look for.
     * @return the corresponding MaintenanceProvisioningState.
     */
    public static MaintenanceProvisioningState fromString(String name) {
        return fromString(name, MaintenanceProvisioningState.class);
    }

    /**
     * Gets known MaintenanceProvisioningState values.
     * 
     * @return known MaintenanceProvisioningState values.
     */
    public static Collection<MaintenanceProvisioningState> values() {
        return values(MaintenanceProvisioningState.class);
    }
}
