# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/migrate/ci.yml
      - sdk/migrate/azure-resourcemanager-migrate/
    exclude:
      - sdk/migrate/pom.xml
      - sdk/migrate/azure-resourcemanager-migrate/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/migrate/ci.yml
      - sdk/migrate/azure-resourcemanager-migrate/
    exclude:
      - sdk/migrate/pom.xml
      - sdk/migrate/azure-resourcemanager-migrate/pom.xml

parameters:
  - name: release_azureresourcemanagermigrate
    displayName: azure-resourcemanager-migrate
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: migrate
    Artifacts:
      - name: azure-resourcemanager-migrate
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagermigrate
        releaseInBatch: ${{ parameters.release_azureresourcemanagermigrate }}
