# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/face/ci.yml
      - sdk/face/azure-ai-face/
    exclude:
      - sdk/face/pom.xml
      - sdk/face/azure-ai-face/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/face/ci.yml
      - sdk/face/azure-ai-face/
    exclude:
      - sdk/face/pom.xml
      - sdk/face/azure-ai-face/pom.xml

parameters:
  - name: release_azureaiface
    displayName: azure-ai-face
    type: boolean
    default: true

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: face
    EnableBatchRelease: true
    Artifacts:
      - name: azure-ai-face
        groupId: com.azure
        safeName: azureaiface
        releaseInBatch: ${{ parameters.release_azureaiface }}
