# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/cosmosdbmongoclusters/ci.yml
      - sdk/cosmosdbmongoclusters/azure-resourcemanager-cosmosdbmongoclusters/
    exclude:
      - sdk/cosmosdbmongoclusters/pom.xml
      - sdk/cosmosdbmongoclusters/azure-resourcemanager-cosmosdbmongoclusters/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/cosmosdbmongoclusters/ci.yml
      - sdk/cosmosdbmongoclusters/azure-resourcemanager-cosmosdbmongoclusters/
    exclude:
      - sdk/cosmosdbmongoclusters/pom.xml
      - sdk/cosmosdbmongoclusters/azure-resourcemanager-cosmosdbmongoclusters/pom.xml

parameters:
  - name: release_azureresourcemanagercosmosdbmongoclusters
    displayName: azure-resourcemanager-cosmosdbmongoclusters
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: cosmosdbmongoclusters
    EnableBatchRelease: true
    Artifacts:
      - name: azure-resourcemanager-cosmosdbmongoclusters
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagercosmosdbmongoclusters
        releaseInBatch: ${{ parameters.release_azureresourcemanagercosmosdbmongoclusters }}
