// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.mcpp.fluent.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.management.ProxyResource;
import com.azure.resourcemanager.mcpp.models.MembershipDetailsResponseProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/** MCPP Purchase details response. */
@Fluent
public final class MembershipDetailsResponseInner extends ProxyResource {
    /*
     * MCPP Purchase details response properties.
     */
    @JsonProperty(value = "properties")
    private MembershipDetailsResponseProperties properties;

    /** Creates an instance of MembershipDetailsResponseInner class. */
    public MembershipDetailsResponseInner() {
    }

    /**
     * Get the properties property: MCPP Purchase details response properties.
     *
     * @return the properties value.
     */
    public MembershipDetailsResponseProperties properties() {
        return this.properties;
    }

    /**
     * Set the properties property: MCPP Purchase details response properties.
     *
     * @param properties the properties value to set.
     * @return the MembershipDetailsResponseInner object itself.
     */
    public MembershipDetailsResponseInner withProperties(MembershipDetailsResponseProperties properties) {
        this.properties = properties;
        return this;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (properties() != null) {
            properties().validate();
        }
    }
}
