// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.resourcemanager.iotoperations.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.util.logging.ClientLogger;
import com.azure.json.JsonReader;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;

/**
 * Microsoft Fabric endpoint.
 */
@Fluent
public final class FabricOneLakeEndpoint extends DataflowEndpointProperties {
    /*
     * Endpoint Type.
     */
    private EndpointType endpointType = EndpointType.FABRIC_ONE_LAKE;

    /*
     * Microsoft Fabric endpoint.
     */
    private FabricOneLakeSettings fabricOneLakeSettings;

    /*
     * The status of the last operation.
     */
    private ProvisioningState provisioningState;

    /**
     * Creates an instance of FabricOneLakeEndpoint class.
     */
    public FabricOneLakeEndpoint() {
    }

    /**
     * Get the endpointType property: Endpoint Type.
     * 
     * @return the endpointType value.
     */
    @Override
    public EndpointType endpointType() {
        return this.endpointType;
    }

    /**
     * Get the fabricOneLakeSettings property: Microsoft Fabric endpoint.
     * 
     * @return the fabricOneLakeSettings value.
     */
    public FabricOneLakeSettings fabricOneLakeSettings() {
        return this.fabricOneLakeSettings;
    }

    /**
     * Set the fabricOneLakeSettings property: Microsoft Fabric endpoint.
     * 
     * @param fabricOneLakeSettings the fabricOneLakeSettings value to set.
     * @return the FabricOneLakeEndpoint object itself.
     */
    public FabricOneLakeEndpoint withFabricOneLakeSettings(FabricOneLakeSettings fabricOneLakeSettings) {
        this.fabricOneLakeSettings = fabricOneLakeSettings;
        return this;
    }

    /**
     * Get the provisioningState property: The status of the last operation.
     * 
     * @return the provisioningState value.
     */
    @Override
    public ProvisioningState provisioningState() {
        return this.provisioningState;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    @Override
    public void validate() {
        if (fabricOneLakeSettings() == null) {
            throw LOGGER.atError()
                .log(new IllegalArgumentException(
                    "Missing required property fabricOneLakeSettings in model FabricOneLakeEndpoint"));
        } else {
            fabricOneLakeSettings().validate();
        }
    }

    private static final ClientLogger LOGGER = new ClientLogger(FabricOneLakeEndpoint.class);

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeJsonField("fabricOneLakeSettings", this.fabricOneLakeSettings);
        jsonWriter.writeStringField("endpointType", this.endpointType == null ? null : this.endpointType.toString());
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of FabricOneLakeEndpoint from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of FabricOneLakeEndpoint if the JsonReader was pointing to an instance of it, or null if it
     * was pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the FabricOneLakeEndpoint.
     */
    public static FabricOneLakeEndpoint fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            FabricOneLakeEndpoint deserializedFabricOneLakeEndpoint = new FabricOneLakeEndpoint();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("provisioningState".equals(fieldName)) {
                    deserializedFabricOneLakeEndpoint.provisioningState
                        = ProvisioningState.fromString(reader.getString());
                } else if ("fabricOneLakeSettings".equals(fieldName)) {
                    deserializedFabricOneLakeEndpoint.fabricOneLakeSettings = FabricOneLakeSettings.fromJson(reader);
                } else if ("endpointType".equals(fieldName)) {
                    deserializedFabricOneLakeEndpoint.endpointType = EndpointType.fromString(reader.getString());
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedFabricOneLakeEndpoint;
        });
    }
}
