// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.mysqldiscovery.fluent.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.management.ProxyResource;
import com.azure.core.management.SystemData;
import com.azure.core.util.logging.ClientLogger;
import com.azure.json.JsonReader;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import com.azure.resourcemanager.mysqldiscovery.models.MysqlServerProperties;
import com.azure.resourcemanager.mysqldiscovery.models.Tag;
import java.io.IOException;
import java.util.List;

/**
 * The MysqlServer resource definition.
 */
@Fluent
public final class MysqlServerInner extends ProxyResource {
    /*
     * Resource properties.
     */
    private MysqlServerProperties properties;

    /*
     * Resource tags
     */
    private List<Tag> tags;

    /*
     * Azure Resource Manager metadata containing createdBy and modifiedBy information.
     */
    private SystemData systemData;

    /*
     * The type of the resource.
     */
    private String type;

    /*
     * The name of the resource.
     */
    private String name;

    /*
     * Fully qualified resource Id for the resource.
     */
    private String id;

    /**
     * Creates an instance of MysqlServerInner class.
     */
    public MysqlServerInner() {
    }

    /**
     * Get the properties property: Resource properties.
     * 
     * @return the properties value.
     */
    public MysqlServerProperties properties() {
        return this.properties;
    }

    /**
     * Set the properties property: Resource properties.
     * 
     * @param properties the properties value to set.
     * @return the MysqlServerInner object itself.
     */
    public MysqlServerInner withProperties(MysqlServerProperties properties) {
        this.properties = properties;
        return this;
    }

    /**
     * Get the tags property: Resource tags.
     * 
     * @return the tags value.
     */
    public List<Tag> tags() {
        return this.tags;
    }

    /**
     * Set the tags property: Resource tags.
     * 
     * @param tags the tags value to set.
     * @return the MysqlServerInner object itself.
     */
    public MysqlServerInner withTags(List<Tag> tags) {
        this.tags = tags;
        return this;
    }

    /**
     * Get the systemData property: Azure Resource Manager metadata containing createdBy and modifiedBy information.
     * 
     * @return the systemData value.
     */
    public SystemData systemData() {
        return this.systemData;
    }

    /**
     * Get the type property: The type of the resource.
     * 
     * @return the type value.
     */
    @Override
    public String type() {
        return this.type;
    }

    /**
     * Get the name property: The name of the resource.
     * 
     * @return the name value.
     */
    @Override
    public String name() {
        return this.name;
    }

    /**
     * Get the id property: Fully qualified resource Id for the resource.
     * 
     * @return the id value.
     */
    @Override
    public String id() {
        return this.id;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (properties() == null) {
            throw LOGGER.atError()
                .log(new IllegalArgumentException("Missing required property properties in model MysqlServerInner"));
        } else {
            properties().validate();
        }
        if (tags() != null) {
            tags().forEach(e -> e.validate());
        }
    }

    private static final ClientLogger LOGGER = new ClientLogger(MysqlServerInner.class);

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeJsonField("properties", this.properties);
        jsonWriter.writeArrayField("tags", this.tags, (writer, element) -> writer.writeJson(element));
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of MysqlServerInner from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of MysqlServerInner if the JsonReader was pointing to an instance of it, or null if it was
     * pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the MysqlServerInner.
     */
    public static MysqlServerInner fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            MysqlServerInner deserializedMysqlServerInner = new MysqlServerInner();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("id".equals(fieldName)) {
                    deserializedMysqlServerInner.id = reader.getString();
                } else if ("name".equals(fieldName)) {
                    deserializedMysqlServerInner.name = reader.getString();
                } else if ("type".equals(fieldName)) {
                    deserializedMysqlServerInner.type = reader.getString();
                } else if ("properties".equals(fieldName)) {
                    deserializedMysqlServerInner.properties = MysqlServerProperties.fromJson(reader);
                } else if ("tags".equals(fieldName)) {
                    List<Tag> tags = reader.readArray(reader1 -> Tag.fromJson(reader1));
                    deserializedMysqlServerInner.tags = tags;
                } else if ("systemData".equals(fieldName)) {
                    deserializedMysqlServerInner.systemData = SystemData.fromJson(reader);
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedMysqlServerInner;
        });
    }
}
