# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/loadtestservicemicrosoftloadtestserviceplaywright/ci.yml
      - sdk/loadtestservicemicrosoftloadtestserviceplaywright/azure-resourcemanager-loadtestservicemicrosoftloadtestserviceplaywright/
    exclude:
      - sdk/loadtestservicemicrosoftloadtestserviceplaywright/pom.xml
      - sdk/loadtestservicemicrosoftloadtestserviceplaywright/azure-resourcemanager-loadtestservicemicrosoftloadtestserviceplaywright/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/loadtestservicemicrosoftloadtestserviceplaywright/ci.yml
      - sdk/loadtestservicemicrosoftloadtestserviceplaywright/azure-resourcemanager-loadtestservicemicrosoftloadtestserviceplaywright/
    exclude:
      - sdk/loadtestservicemicrosoftloadtestserviceplaywright/pom.xml
      - sdk/loadtestservicemicrosoftloadtestserviceplaywright/azure-resourcemanager-loadtestservicemicrosoftloadtestserviceplaywright/pom.xml

parameters:
  - name: release_azureresourcemanagerloadtestservicemicrosoftloadtestserviceplaywright
    displayName: azure-resourcemanager-loadtestservicemicrosoftloadtestserviceplaywright
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: loadtestservicemicrosoftloadtestserviceplaywright
    Artifacts:
      - name: azure-resourcemanager-loadtestservicemicrosoftloadtestserviceplaywright
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerloadtestservicemicrosoftloadtestserviceplaywright
        releaseInBatch: ${{ parameters.release_azureresourcemanagerloadtestservicemicrosoftloadtestserviceplaywright }}
