# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/resourcesmicrosoftresourcesbicep/ci.yml
      - sdk/resourcesmicrosoftresourcesbicep/azure-resourcemanager-resourcesmicrosoftresourcesbicep/
    exclude:
      - sdk/resourcesmicrosoftresourcesbicep/pom.xml
      - sdk/resourcesmicrosoftresourcesbicep/azure-resourcemanager-resourcesmicrosoftresourcesbicep/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/resourcesmicrosoftresourcesbicep/ci.yml
      - sdk/resourcesmicrosoftresourcesbicep/azure-resourcemanager-resourcesmicrosoftresourcesbicep/
    exclude:
      - sdk/resourcesmicrosoftresourcesbicep/pom.xml
      - sdk/resourcesmicrosoftresourcesbicep/azure-resourcemanager-resourcesmicrosoftresourcesbicep/pom.xml

parameters:
  - name: release_azureresourcemanagerresourcesmicrosoftresourcesbicep
    displayName: azure-resourcemanager-resourcesmicrosoftresourcesbicep
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: resourcesmicrosoftresourcesbicep
    Artifacts:
      - name: azure-resourcemanager-resourcesmicrosoftresourcesbicep
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerresourcesmicrosoftresourcesbicep
        releaseInBatch: ${{ parameters.release_azureresourcemanagerresourcesmicrosoftresourcesbicep }}
