# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/vision/ci.yml
      - sdk/vision/azure-ai-vision-imageanalysis/
    exclude:
      - sdk/vision/pom.xml
      - sdk/vision/azure-ai-vision-imageanalysis/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/vision/ci.yml
      - sdk/vision/azure-ai-vision-imageanalysis/
    exclude:
      - sdk/vision/pom.xml
      - sdk/vision/azure-ai-vision-imageanalysis/pom.xml

parameters:
  - name: release_azureaivisionimageanalysis
    displayName: azure-ai-vision-imageanalysis
    type: boolean
    default: true
  - name: release_azureaivisionface
    displayName: azure-ai-vision-face
    type: boolean
    default: true

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: vision
    EnableBatchRelease: true
    IgnoreVerifyTypeSpecCodeGenerationError: true
    Artifacts:
      - name: azure-ai-vision-imageanalysis
        groupId: com.azure
        safeName: azureaivisionimageanalysis
        releaseInBatch: ${{ parameters.release_azureaivisionimageanalysis }}
      - name: azure-ai-vision-face
        groupId: com.azure
        safeName: azureaivisionface
        releaseInBatch: ${{ parameters.release_azureaivisionface }}
