# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/playwrightservice/ci.yml
      - sdk/playwrightservice/azure-resourcemanager-playwrightservice/
    exclude:
      - sdk/playwrightservice/pom.xml
      - sdk/playwrightservice/azure-resourcemanager-playwrightservice/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/playwrightservice/ci.yml
      - sdk/playwrightservice/azure-resourcemanager-playwrightservice/
    exclude:
      - sdk/playwrightservice/pom.xml
      - sdk/playwrightservice/azure-resourcemanager-playwrightservice/pom.xml

parameters:
  - name: release_azureresourcemanagerplaywrightservice
    displayName: azure-resourcemanager-playwrightservice
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: playwrightservice
    Artifacts:
      - name: azure-resourcemanager-playwrightservice
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerplaywrightservice
        releaseInBatch: ${{ parameters.release_azureresourcemanagerplaywrightservice }}
