# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/portalservices/ci.yml
      - sdk/portalservices/azure-resourcemanager-portalservices/
    exclude:
      - sdk/portalservices/pom.xml
      - sdk/portalservices/azure-resourcemanager-portalservices/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/portalservices/ci.yml
      - sdk/portalservices/azure-resourcemanager-portalservices/
    exclude:
      - sdk/portalservices/pom.xml
      - sdk/portalservices/azure-resourcemanager-portalservices/pom.xml

parameters:
  - name: release_azureresourcemanagerportalservices
    displayName: azure-resourcemanager-portalservices
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: portalservices
    Artifacts:
      - name: azure-resourcemanager-portalservices
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerportalservices
        releaseInBatch: ${{ parameters.release_azureresourcemanagerportalservices }}
