# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/manufacturingdatasolution/ci.yml
      - sdk/manufacturingdatasolution/azure-microsoft-industry-manufacturing-mds-copilot/
    exclude:
      - sdk/manufacturingdatasolution/pom.xml
      - sdk/manufacturingdatasolution/azure-microsoft-industry-manufacturing-mds-copilot/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/manufacturingdatasolution/ci.yml
      - sdk/manufacturingdatasolution/azure-microsoft-industry-manufacturing-mds-copilot/
    exclude:
      - sdk/manufacturingdatasolution/pom.xml
      - sdk/manufacturingdatasolution/azure-microsoft-industry-manufacturing-mds-copilot/pom.xml

parameters:
  - name: release_azuremicrosoftindustrymanufacturingmdscopilot
    displayName: azure-microsoft-industry-manufacturing-mds-copilot
    type: boolean
    default: true

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: manufacturingdatasolution
    Artifacts:
      - name: azure-microsoft-industry-manufacturing-mds-copilot
        groupId: com.azure
        safeName: azuremicrosoftindustrymanufacturingmdscopilot
        releaseInBatch: ${{ parameters.release_azuremicrosoftindustrymanufacturingmdscopilot }}
