# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/iotoperationsmq/ci.yml
      - sdk/iotoperationsmq/azure-resourcemanager-iotoperationsmq/
    exclude:
      - sdk/iotoperationsmq/pom.xml
      - sdk/iotoperationsmq/azure-resourcemanager-iotoperationsmq/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/iotoperationsmq/ci.yml
      - sdk/iotoperationsmq/azure-resourcemanager-iotoperationsmq/
    exclude:
      - sdk/iotoperationsmq/pom.xml
      - sdk/iotoperationsmq/azure-resourcemanager-iotoperationsmq/pom.xml

parameters:
  - name: release_azureresourcemanageriotoperationsmq
    displayName: azure-resourcemanager-iotoperationsmq
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: iotoperationsmq
    EnableBatchRelease: true
    Artifacts:
      - name: azure-resourcemanager-iotoperationsmq
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanageriotoperationsmq
        releaseInBatch: ${{ parameters.release_azureresourcemanageriotoperationsmq }}
