# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/onlineexperimentation/ci.yml
      - sdk/onlineexperimentation/azure-resourcemanager-onlineexperimentation/
    exclude:
      - sdk/onlineexperimentation/pom.xml
      - sdk/onlineexperimentation/azure-resourcemanager-onlineexperimentation/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/onlineexperimentation/ci.yml
      - sdk/onlineexperimentation/azure-resourcemanager-onlineexperimentation/
    exclude:
      - sdk/onlineexperimentation/pom.xml
      - sdk/onlineexperimentation/azure-resourcemanager-onlineexperimentation/pom.xml

parameters:
  - name: release_azureresourcemanageronlineexperimentation
    displayName: azure-resourcemanager-onlineexperimentation
    type: boolean
    default: false
  - name: release_azureanalyticsonlineexperimentation
    displayName: azure-analytics-onlineexperimentation
    type: boolean
    default: true

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: onlineexperimentation
    Artifacts:
      - name: azure-resourcemanager-onlineexperimentation
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanageronlineexperimentation
        releaseInBatch: ${{ parameters.release_azureresourcemanageronlineexperimentation }}
      - name: azure-analytics-onlineexperimentation
        groupId: com.azure
        safeName: azureanalyticsonlineexperimentation
        releaseInBatch: ${{ parameters.release_azureanalyticsonlineexperimentation }}
